
package pe.com.certicom.scolas.monitor.clientws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MonitorWS", targetNamespace = "http://service.scolas.certicom.com.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MonitorWS {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://service.scolas.certicom.com.pe/", className = "pe.com.certicom.scolas.monitor.clientws.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://service.scolas.certicom.com.pe/", className = "pe.com.certicom.scolas.monitor.clientws.PingResponse")
    public String ping();

    /**
     * 
     * @param mensaje
     */
    @WebMethod
    @RequestWrapper(localName = "publicar", targetNamespace = "http://service.scolas.certicom.com.pe/", className = "pe.com.certicom.scolas.monitor.clientws.Publicar")
    @ResponseWrapper(localName = "publicarResponse", targetNamespace = "http://service.scolas.certicom.com.pe/", className = "pe.com.certicom.scolas.monitor.clientws.PublicarResponse")
    public void publicar(
        @WebParam(name = "mensaje", targetNamespace = "")
        String mensaje);

}
