
package pe.com.certicom.scolas.monitor.clientws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MonitorWSService", targetNamespace = "http://service.scolas.certicom.com.pe/", wsdlLocation = "http://localhost:8080/monitor/MonitorWS?wsdl")
public class MonitorWSService
    extends Service
{

    private final static URL MONITORWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(pe.com.certicom.scolas.monitor.clientws.MonitorWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = pe.com.certicom.scolas.monitor.clientws.MonitorWSService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/monitor/MonitorWS?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/monitor/MonitorWS?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MONITORWSSERVICE_WSDL_LOCATION = url;
    }

    public MonitorWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MonitorWSService() {
        super(MONITORWSSERVICE_WSDL_LOCATION, new QName("http://service.scolas.certicom.com.pe/", "MonitorWSService"));
    }

    /**
     * 
     * @return
     *     returns MonitorWS
     */
    @WebEndpoint(name = "MonitorWSPort")
    public MonitorWS getMonitorWSPort() {
        return super.getPort(new QName("http://service.scolas.certicom.com.pe/", "MonitorWSPort"), MonitorWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MonitorWS
     */
    @WebEndpoint(name = "MonitorWSPort")
    public MonitorWS getMonitorWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.scolas.certicom.com.pe/", "MonitorWSPort"), MonitorWS.class, features);
    }

}
