package pe.com.certicom.scolas.model.dao;

import java.util.List;
import pe.com.certicom.scolas.model.beans.ConfiguracionMonitor;
import pe.com.certicom.scolas.model.beans.ConfiguracionMonitorExample;
import pe.com.certicom.scolas.model.beans.ConfiguracionMonitorKey;

public interface ConfiguracionMonitorDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    int countByExample(ConfiguracionMonitorExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    int deleteByExample(ConfiguracionMonitorExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    int deleteByPrimaryKey(ConfiguracionMonitorKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    void insert(ConfiguracionMonitor record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    void insertSelective(ConfiguracionMonitor record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    List<ConfiguracionMonitor> selectByExample(ConfiguracionMonitorExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    ConfiguracionMonitor selectByPrimaryKey(ConfiguracionMonitorKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    int updateByExampleSelective(ConfiguracionMonitor record, ConfiguracionMonitorExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    int updateByExample(ConfiguracionMonitor record, ConfiguracionMonitorExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    int updateByPrimaryKeySelective(ConfiguracionMonitor record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    int updateByPrimaryKey(ConfiguracionMonitor record);

    ConfiguracionMonitor getConfiguracionMonitor(Integer idConfiguracion);

    void conectarMonitor(Integer idConfiguracion);

    void desconectarMonitor(Integer idConfiguracion);
}