package pe.com.certicom.scolas.model.dao;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.com.certicom.scolas.model.beans.ConfiguracionMonitor;
import pe.com.certicom.scolas.model.beans.ConfiguracionMonitorExample;
import pe.com.certicom.scolas.model.beans.ConfiguracionMonitorKey;

public class ConfiguracionMonitorDAOImpl extends SqlMapClientDaoSupport implements ConfiguracionMonitorDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public ConfiguracionMonitorDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public int countByExample(ConfiguracionMonitorExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("configuracion_emisor_llamados.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public int deleteByExample(ConfiguracionMonitorExample example) {
        int rows = getSqlMapClientTemplate().delete("configuracion_emisor_llamados.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public int deleteByPrimaryKey(ConfiguracionMonitorKey key) {
        int rows = getSqlMapClientTemplate().delete("configuracion_emisor_llamados.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void insert(ConfiguracionMonitor record) {
        getSqlMapClientTemplate().insert("configuracion_emisor_llamados.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void insertSelective(ConfiguracionMonitor record) {
        getSqlMapClientTemplate().insert("configuracion_emisor_llamados.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    @SuppressWarnings("unchecked")
    public List<ConfiguracionMonitor> selectByExample(ConfiguracionMonitorExample example) {
        List<ConfiguracionMonitor> list = getSqlMapClientTemplate().queryForList("configuracion_emisor_llamados.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public ConfiguracionMonitor selectByPrimaryKey(ConfiguracionMonitorKey key) {
        ConfiguracionMonitor record = (ConfiguracionMonitor) getSqlMapClientTemplate().queryForObject("configuracion_emisor_llamados.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public int updateByExampleSelective(ConfiguracionMonitor record, ConfiguracionMonitorExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("configuracion_emisor_llamados.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public int updateByExample(ConfiguracionMonitor record, ConfiguracionMonitorExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("configuracion_emisor_llamados.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public int updateByPrimaryKeySelective(ConfiguracionMonitor record) {
        int rows = getSqlMapClientTemplate().update("configuracion_emisor_llamados.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public int updateByPrimaryKey(ConfiguracionMonitor record) {
        int rows = getSqlMapClientTemplate().update("configuracion_emisor_llamados.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    public ConfiguracionMonitor getConfiguracionMonitor(Integer idConfiguracion) {
        ConfiguracionMonitor record = (ConfiguracionMonitor) getSqlMapClientTemplate().queryForObject(
                "configuracion_emisor_llamados.getConfiguracionMonitor", idConfiguracion);
        return record;
    }

    public void conectarMonitor(Integer idConfiguracion) {
        getSqlMapClientTemplate().update("configuracion_emisor_llamados.conectarMonitor", idConfiguracion);
    }

    public void desconectarMonitor(Integer idConfiguracion) {
        getSqlMapClientTemplate().update("configuracion_emisor_llamados.desconectarMonitor", idConfiguracion);
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private static class UpdateByExampleParms extends ConfiguracionMonitorExample {
        private Object record;

        public UpdateByExampleParms(Object record, ConfiguracionMonitorExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}