package pe.com.certicom.scolas.model.dao;

import java.util.List;
import pe.com.certicom.scolas.model.beans.GrillaLlamados;
import pe.com.certicom.scolas.model.beans.GrillaLlamadosExample;

public interface GrillaLlamadosDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    int countByExample(GrillaLlamadosExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    int deleteByExample(GrillaLlamadosExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    int deleteByPrimaryKey(Integer idGrillaLlamados);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    void insert(GrillaLlamados record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    void insertSelective(GrillaLlamados record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    List<GrillaLlamados> selectByExample(GrillaLlamadosExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    GrillaLlamados selectByPrimaryKey(Integer idGrillaLlamados);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    int updateByExampleSelective(GrillaLlamados record, GrillaLlamadosExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    int updateByExample(GrillaLlamados record, GrillaLlamadosExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    int updateByPrimaryKeySelective(GrillaLlamados record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    int updateByPrimaryKey(GrillaLlamados record);

    GrillaLlamados getConfiguracionGrilla(Integer idConfiguracion);
}