package pe.com.certicom.scolas.model.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.com.certicom.scolas.model.beans.Video;
import pe.com.certicom.scolas.model.beans.VideoExample;

public class VideoDAOImpl extends SqlMapClientDaoSupport implements VideoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public VideoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public int countByExample(VideoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("VIDEO.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public int deleteByExample(VideoExample example) {
        int rows = getSqlMapClientTemplate().delete("VIDEO.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public int deleteByPrimaryKey(Integer idVideo) {
        Video key = new Video();
        key.setIdVideo(idVideo);
        int rows = getSqlMapClientTemplate().delete("VIDEO.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void insert(Video record) {
        getSqlMapClientTemplate().insert("VIDEO.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void insertSelective(Video record) {
        getSqlMapClientTemplate().insert("VIDEO.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    @SuppressWarnings("unchecked")
    public List<Video> selectByExample(VideoExample example) {
        List<Video> list = getSqlMapClientTemplate().queryForList("VIDEO.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public Video selectByPrimaryKey(Integer idVideo) {
        Video key = new Video();
        key.setIdVideo(idVideo);
        Video record = (Video) getSqlMapClientTemplate().queryForObject("VIDEO.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public int updateByExampleSelective(Video record, VideoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("VIDEO.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public int updateByExample(Video record, VideoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("VIDEO.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public int updateByPrimaryKeySelective(Video record) {
        int rows = getSqlMapClientTemplate().update("VIDEO.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public int updateByPrimaryKey(Video record) {
        int rows = getSqlMapClientTemplate().update("VIDEO.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    public List<Video> listarVideos(Integer idConfiguracion) {
        Map<String,Integer> parametros = new HashMap<String,Integer>();
        parametros.put("idConfiguracion",idConfiguracion);
        List<Video> list = getSqlMapClientTemplate().queryForList("VIDEO.listarVideos",parametros);
        return list;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    private static class UpdateByExampleParms extends VideoExample {
        private Object record;

        public UpdateByExampleParms(Object record, VideoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}