package pe.com.certicom.scolas.model.beans;

public class ConfiguracionMonitor extends ConfiguracionMonitorKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_pos_app_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numPosAppX;
    
    private String indConectado;

    private Integer idEspacioAtencion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_pos_app_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numPosAppY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_dim_app_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numDimAppX;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_dim_app_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numDimAppY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_pos_video_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numPosVideoX;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_pos_video_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numPosVideoY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_dim_video_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numDimVideoX;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_dim_video_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numDimVideoY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_pos_marquesina_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numPosMarquesinaX;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_pos_marquesina_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numPosMarquesinaY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_dim_marquesina_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numDimMarquesinaX;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_dim_marquesina_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numDimMarquesinaY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_pos_grilla_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numPosGrillaX;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_pos_grilla_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numPosGrillaY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_dim_grilla_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numDimGrillaX;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.num_dim_grilla_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer numDimGrillaY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.ind_mouse_visualizado
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private String indMouseVisualizado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_pos_app_x
     *
     * @return the value of configuracion_emisor_llamados.num_pos_app_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumPosAppX() {
        return numPosAppX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_pos_app_x
     *
     * @param numPosAppX the value for configuracion_emisor_llamados.num_pos_app_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumPosAppX(Integer numPosAppX) {
        this.numPosAppX = numPosAppX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_pos_app_y
     *
     * @return the value of configuracion_emisor_llamados.num_pos_app_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumPosAppY() {
        return numPosAppY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_pos_app_y
     *
     * @param numPosAppY the value for configuracion_emisor_llamados.num_pos_app_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumPosAppY(Integer numPosAppY) {
        this.numPosAppY = numPosAppY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_dim_app_x
     *
     * @return the value of configuracion_emisor_llamados.num_dim_app_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumDimAppX() {
        return numDimAppX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_dim_app_x
     *
     * @param numDimAppX the value for configuracion_emisor_llamados.num_dim_app_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumDimAppX(Integer numDimAppX) {
        this.numDimAppX = numDimAppX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_dim_app_y
     *
     * @return the value of configuracion_emisor_llamados.num_dim_app_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumDimAppY() {
        return numDimAppY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_dim_app_y
     *
     * @param numDimAppY the value for configuracion_emisor_llamados.num_dim_app_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumDimAppY(Integer numDimAppY) {
        this.numDimAppY = numDimAppY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_pos_video_x
     *
     * @return the value of configuracion_emisor_llamados.num_pos_video_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumPosVideoX() {
        return numPosVideoX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_pos_video_x
     *
     * @param numPosVideoX the value for configuracion_emisor_llamados.num_pos_video_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumPosVideoX(Integer numPosVideoX) {
        this.numPosVideoX = numPosVideoX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_pos_video_y
     *
     * @return the value of configuracion_emisor_llamados.num_pos_video_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumPosVideoY() {
        return numPosVideoY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_pos_video_y
     *
     * @param numPosVideoY the value for configuracion_emisor_llamados.num_pos_video_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumPosVideoY(Integer numPosVideoY) {
        this.numPosVideoY = numPosVideoY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_dim_video_x
     *
     * @return the value of configuracion_emisor_llamados.num_dim_video_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumDimVideoX() {
        return numDimVideoX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_dim_video_x
     *
     * @param numDimVideoX the value for configuracion_emisor_llamados.num_dim_video_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumDimVideoX(Integer numDimVideoX) {
        this.numDimVideoX = numDimVideoX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_dim_video_y
     *
     * @return the value of configuracion_emisor_llamados.num_dim_video_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumDimVideoY() {
        return numDimVideoY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_dim_video_y
     *
     * @param numDimVideoY the value for configuracion_emisor_llamados.num_dim_video_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumDimVideoY(Integer numDimVideoY) {
        this.numDimVideoY = numDimVideoY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_pos_marquesina_x
     *
     * @return the value of configuracion_emisor_llamados.num_pos_marquesina_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumPosMarquesinaX() {
        return numPosMarquesinaX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_pos_marquesina_x
     *
     * @param numPosMarquesinaX the value for configuracion_emisor_llamados.num_pos_marquesina_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumPosMarquesinaX(Integer numPosMarquesinaX) {
        this.numPosMarquesinaX = numPosMarquesinaX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_pos_marquesina_y
     *
     * @return the value of configuracion_emisor_llamados.num_pos_marquesina_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumPosMarquesinaY() {
        return numPosMarquesinaY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_pos_marquesina_y
     *
     * @param numPosMarquesinaY the value for configuracion_emisor_llamados.num_pos_marquesina_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumPosMarquesinaY(Integer numPosMarquesinaY) {
        this.numPosMarquesinaY = numPosMarquesinaY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_dim_marquesina_x
     *
     * @return the value of configuracion_emisor_llamados.num_dim_marquesina_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumDimMarquesinaX() {
        return numDimMarquesinaX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_dim_marquesina_x
     *
     * @param numDimMarquesinaX the value for configuracion_emisor_llamados.num_dim_marquesina_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumDimMarquesinaX(Integer numDimMarquesinaX) {
        this.numDimMarquesinaX = numDimMarquesinaX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_dim_marquesina_y
     *
     * @return the value of configuracion_emisor_llamados.num_dim_marquesina_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumDimMarquesinaY() {
        return numDimMarquesinaY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_dim_marquesina_y
     *
     * @param numDimMarquesinaY the value for configuracion_emisor_llamados.num_dim_marquesina_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumDimMarquesinaY(Integer numDimMarquesinaY) {
        this.numDimMarquesinaY = numDimMarquesinaY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_pos_grilla_x
     *
     * @return the value of configuracion_emisor_llamados.num_pos_grilla_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumPosGrillaX() {
        return numPosGrillaX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_pos_grilla_x
     *
     * @param numPosGrillaX the value for configuracion_emisor_llamados.num_pos_grilla_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumPosGrillaX(Integer numPosGrillaX) {
        this.numPosGrillaX = numPosGrillaX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_pos_grilla_y
     *
     * @return the value of configuracion_emisor_llamados.num_pos_grilla_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumPosGrillaY() {
        return numPosGrillaY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_pos_grilla_y
     *
     * @param numPosGrillaY the value for configuracion_emisor_llamados.num_pos_grilla_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumPosGrillaY(Integer numPosGrillaY) {
        this.numPosGrillaY = numPosGrillaY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_dim_grilla_x
     *
     * @return the value of configuracion_emisor_llamados.num_dim_grilla_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumDimGrillaX() {
        return numDimGrillaX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_dim_grilla_x
     *
     * @param numDimGrillaX the value for configuracion_emisor_llamados.num_dim_grilla_x
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumDimGrillaX(Integer numDimGrillaX) {
        this.numDimGrillaX = numDimGrillaX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.num_dim_grilla_y
     *
     * @return the value of configuracion_emisor_llamados.num_dim_grilla_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getNumDimGrillaY() {
        return numDimGrillaY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.num_dim_grilla_y
     *
     * @param numDimGrillaY the value for configuracion_emisor_llamados.num_dim_grilla_y
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setNumDimGrillaY(Integer numDimGrillaY) {
        this.numDimGrillaY = numDimGrillaY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.ind_mouse_visualizado
     *
     * @return the value of configuracion_emisor_llamados.ind_mouse_visualizado
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public String getIndMouseVisualizado() {
        return indMouseVisualizado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.ind_mouse_visualizado
     *
     * @param indMouseVisualizado the value for configuracion_emisor_llamados.ind_mouse_visualizado
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setIndMouseVisualizado(String indMouseVisualizado) {
        this.indMouseVisualizado = indMouseVisualizado == null ? null : indMouseVisualizado.trim();
    }

    /**
     * @return the indConectado
     */
    public String getIndConectado() {
        return indConectado;
    }

    /**
     * @param indConectado the indConectado to set
     */
    public void setIndConectado(String indConectado) {
        this.indConectado = indConectado;
    }

    /**
     * @return the idEspacioAtencion
     */
    public Integer getIdEspacioAtencion() {
        return idEspacioAtencion;
    }

    /**
     * @param idEspacioAtencion the idEspacioAtencion to set
     */
    public void setIdEspacioAtencion(Integer idEspacioAtencion) {
        this.idEspacioAtencion = idEspacioAtencion;
    }
}