package pe.com.certicom.scolas.model.beans;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GrillaLlamadosExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table grilla_llamados
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table grilla_llamados
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grilla_llamados
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public GrillaLlamadosExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grilla_llamados
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    protected GrillaLlamadosExample(GrillaLlamadosExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grilla_llamados
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grilla_llamados
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grilla_llamados
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grilla_llamados
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grilla_llamados
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grilla_llamados
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table grilla_llamados
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table grilla_llamados
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdGrillaLlamadosIsNull() {
            addCriterion("id_grilla_llamados is null");
            return this;
        }

        public Criteria andIdGrillaLlamadosIsNotNull() {
            addCriterion("id_grilla_llamados is not null");
            return this;
        }

        public Criteria andIdGrillaLlamadosEqualTo(Integer value) {
            addCriterion("id_grilla_llamados =", value, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosNotEqualTo(Integer value) {
            addCriterion("id_grilla_llamados <>", value, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosGreaterThan(Integer value) {
            addCriterion("id_grilla_llamados >", value, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_grilla_llamados >=", value, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosLessThan(Integer value) {
            addCriterion("id_grilla_llamados <", value, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosLessThanOrEqualTo(Integer value) {
            addCriterion("id_grilla_llamados <=", value, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosIn(List<Integer> values) {
            addCriterion("id_grilla_llamados in", values, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosNotIn(List<Integer> values) {
            addCriterion("id_grilla_llamados not in", values, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosBetween(Integer value1, Integer value2) {
            addCriterion("id_grilla_llamados between", value1, value2, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosNotBetween(Integer value1, Integer value2) {
            addCriterion("id_grilla_llamados not between", value1, value2, "idGrillaLlamados");
            return this;
        }

        public Criteria andNumFilasIsNull() {
            addCriterion("num_filas is null");
            return this;
        }

        public Criteria andNumFilasIsNotNull() {
            addCriterion("num_filas is not null");
            return this;
        }

        public Criteria andNumFilasEqualTo(Integer value) {
            addCriterion("num_filas =", value, "numFilas");
            return this;
        }

        public Criteria andNumFilasNotEqualTo(Integer value) {
            addCriterion("num_filas <>", value, "numFilas");
            return this;
        }

        public Criteria andNumFilasGreaterThan(Integer value) {
            addCriterion("num_filas >", value, "numFilas");
            return this;
        }

        public Criteria andNumFilasGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_filas >=", value, "numFilas");
            return this;
        }

        public Criteria andNumFilasLessThan(Integer value) {
            addCriterion("num_filas <", value, "numFilas");
            return this;
        }

        public Criteria andNumFilasLessThanOrEqualTo(Integer value) {
            addCriterion("num_filas <=", value, "numFilas");
            return this;
        }

        public Criteria andNumFilasIn(List<Integer> values) {
            addCriterion("num_filas in", values, "numFilas");
            return this;
        }

        public Criteria andNumFilasNotIn(List<Integer> values) {
            addCriterion("num_filas not in", values, "numFilas");
            return this;
        }

        public Criteria andNumFilasBetween(Integer value1, Integer value2) {
            addCriterion("num_filas between", value1, value2, "numFilas");
            return this;
        }

        public Criteria andNumFilasNotBetween(Integer value1, Integer value2) {
            addCriterion("num_filas not between", value1, value2, "numFilas");
            return this;
        }

        public Criteria andNumColumnasIsNull() {
            addCriterion("num_columnas is null");
            return this;
        }

        public Criteria andNumColumnasIsNotNull() {
            addCriterion("num_columnas is not null");
            return this;
        }

        public Criteria andNumColumnasEqualTo(Integer value) {
            addCriterion("num_columnas =", value, "numColumnas");
            return this;
        }

        public Criteria andNumColumnasNotEqualTo(Integer value) {
            addCriterion("num_columnas <>", value, "numColumnas");
            return this;
        }

        public Criteria andNumColumnasGreaterThan(Integer value) {
            addCriterion("num_columnas >", value, "numColumnas");
            return this;
        }

        public Criteria andNumColumnasGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_columnas >=", value, "numColumnas");
            return this;
        }

        public Criteria andNumColumnasLessThan(Integer value) {
            addCriterion("num_columnas <", value, "numColumnas");
            return this;
        }

        public Criteria andNumColumnasLessThanOrEqualTo(Integer value) {
            addCriterion("num_columnas <=", value, "numColumnas");
            return this;
        }

        public Criteria andNumColumnasIn(List<Integer> values) {
            addCriterion("num_columnas in", values, "numColumnas");
            return this;
        }

        public Criteria andNumColumnasNotIn(List<Integer> values) {
            addCriterion("num_columnas not in", values, "numColumnas");
            return this;
        }

        public Criteria andNumColumnasBetween(Integer value1, Integer value2) {
            addCriterion("num_columnas between", value1, value2, "numColumnas");
            return this;
        }

        public Criteria andNumColumnasNotBetween(Integer value1, Integer value2) {
            addCriterion("num_columnas not between", value1, value2, "numColumnas");
            return this;
        }

        public Criteria andNumColorFondoRIsNull() {
            addCriterion("num_color_fondo_R is null");
            return this;
        }

        public Criteria andNumColorFondoRIsNotNull() {
            addCriterion("num_color_fondo_R is not null");
            return this;
        }

        public Criteria andNumColorFondoREqualTo(Integer value) {
            addCriterion("num_color_fondo_R =", value, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRNotEqualTo(Integer value) {
            addCriterion("num_color_fondo_R <>", value, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRGreaterThan(Integer value) {
            addCriterion("num_color_fondo_R >", value, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_fondo_R >=", value, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRLessThan(Integer value) {
            addCriterion("num_color_fondo_R <", value, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_fondo_R <=", value, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRIn(List<Integer> values) {
            addCriterion("num_color_fondo_R in", values, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRNotIn(List<Integer> values) {
            addCriterion("num_color_fondo_R not in", values, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRBetween(Integer value1, Integer value2) {
            addCriterion("num_color_fondo_R between", value1, value2, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_fondo_R not between", value1, value2, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoGIsNull() {
            addCriterion("num_color_fondo_G is null");
            return this;
        }

        public Criteria andNumColorFondoGIsNotNull() {
            addCriterion("num_color_fondo_G is not null");
            return this;
        }

        public Criteria andNumColorFondoGEqualTo(Integer value) {
            addCriterion("num_color_fondo_G =", value, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGNotEqualTo(Integer value) {
            addCriterion("num_color_fondo_G <>", value, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGGreaterThan(Integer value) {
            addCriterion("num_color_fondo_G >", value, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_fondo_G >=", value, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGLessThan(Integer value) {
            addCriterion("num_color_fondo_G <", value, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_fondo_G <=", value, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGIn(List<Integer> values) {
            addCriterion("num_color_fondo_G in", values, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGNotIn(List<Integer> values) {
            addCriterion("num_color_fondo_G not in", values, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGBetween(Integer value1, Integer value2) {
            addCriterion("num_color_fondo_G between", value1, value2, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_fondo_G not between", value1, value2, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoBIsNull() {
            addCriterion("num_color_fondo_B is null");
            return this;
        }

        public Criteria andNumColorFondoBIsNotNull() {
            addCriterion("num_color_fondo_B is not null");
            return this;
        }

        public Criteria andNumColorFondoBEqualTo(Integer value) {
            addCriterion("num_color_fondo_B =", value, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBNotEqualTo(Integer value) {
            addCriterion("num_color_fondo_B <>", value, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBGreaterThan(Integer value) {
            addCriterion("num_color_fondo_B >", value, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_fondo_B >=", value, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBLessThan(Integer value) {
            addCriterion("num_color_fondo_B <", value, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_fondo_B <=", value, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBIn(List<Integer> values) {
            addCriterion("num_color_fondo_B in", values, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBNotIn(List<Integer> values) {
            addCriterion("num_color_fondo_B not in", values, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBBetween(Integer value1, Integer value2) {
            addCriterion("num_color_fondo_B between", value1, value2, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_fondo_B not between", value1, value2, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorTextoRIsNull() {
            addCriterion("num_color_texto_R is null");
            return this;
        }

        public Criteria andNumColorTextoRIsNotNull() {
            addCriterion("num_color_texto_R is not null");
            return this;
        }

        public Criteria andNumColorTextoREqualTo(Integer value) {
            addCriterion("num_color_texto_R =", value, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRNotEqualTo(Integer value) {
            addCriterion("num_color_texto_R <>", value, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRGreaterThan(Integer value) {
            addCriterion("num_color_texto_R >", value, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_texto_R >=", value, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRLessThan(Integer value) {
            addCriterion("num_color_texto_R <", value, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_texto_R <=", value, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRIn(List<Integer> values) {
            addCriterion("num_color_texto_R in", values, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRNotIn(List<Integer> values) {
            addCriterion("num_color_texto_R not in", values, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRBetween(Integer value1, Integer value2) {
            addCriterion("num_color_texto_R between", value1, value2, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_texto_R not between", value1, value2, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoGIsNull() {
            addCriterion("num_color_texto_G is null");
            return this;
        }

        public Criteria andNumColorTextoGIsNotNull() {
            addCriterion("num_color_texto_G is not null");
            return this;
        }

        public Criteria andNumColorTextoGEqualTo(Integer value) {
            addCriterion("num_color_texto_G =", value, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGNotEqualTo(Integer value) {
            addCriterion("num_color_texto_G <>", value, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGGreaterThan(Integer value) {
            addCriterion("num_color_texto_G >", value, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_texto_G >=", value, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGLessThan(Integer value) {
            addCriterion("num_color_texto_G <", value, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_texto_G <=", value, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGIn(List<Integer> values) {
            addCriterion("num_color_texto_G in", values, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGNotIn(List<Integer> values) {
            addCriterion("num_color_texto_G not in", values, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGBetween(Integer value1, Integer value2) {
            addCriterion("num_color_texto_G between", value1, value2, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_texto_G not between", value1, value2, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoBIsNull() {
            addCriterion("num_color_texto_B is null");
            return this;
        }

        public Criteria andNumColorTextoBIsNotNull() {
            addCriterion("num_color_texto_B is not null");
            return this;
        }

        public Criteria andNumColorTextoBEqualTo(Integer value) {
            addCriterion("num_color_texto_B =", value, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBNotEqualTo(Integer value) {
            addCriterion("num_color_texto_B <>", value, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBGreaterThan(Integer value) {
            addCriterion("num_color_texto_B >", value, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_texto_B >=", value, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBLessThan(Integer value) {
            addCriterion("num_color_texto_B <", value, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_texto_B <=", value, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBIn(List<Integer> values) {
            addCriterion("num_color_texto_B in", values, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBNotIn(List<Integer> values) {
            addCriterion("num_color_texto_B not in", values, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBBetween(Integer value1, Integer value2) {
            addCriterion("num_color_texto_B between", value1, value2, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_texto_B not between", value1, value2, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorResaltadoRIsNull() {
            addCriterion("num_color_resaltado_R is null");
            return this;
        }

        public Criteria andNumColorResaltadoRIsNotNull() {
            addCriterion("num_color_resaltado_R is not null");
            return this;
        }

        public Criteria andNumColorResaltadoREqualTo(Integer value) {
            addCriterion("num_color_resaltado_R =", value, "numColorResaltadoR");
            return this;
        }

        public Criteria andNumColorResaltadoRNotEqualTo(Integer value) {
            addCriterion("num_color_resaltado_R <>", value, "numColorResaltadoR");
            return this;
        }

        public Criteria andNumColorResaltadoRGreaterThan(Integer value) {
            addCriterion("num_color_resaltado_R >", value, "numColorResaltadoR");
            return this;
        }

        public Criteria andNumColorResaltadoRGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_resaltado_R >=", value, "numColorResaltadoR");
            return this;
        }

        public Criteria andNumColorResaltadoRLessThan(Integer value) {
            addCriterion("num_color_resaltado_R <", value, "numColorResaltadoR");
            return this;
        }

        public Criteria andNumColorResaltadoRLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_resaltado_R <=", value, "numColorResaltadoR");
            return this;
        }

        public Criteria andNumColorResaltadoRIn(List<Integer> values) {
            addCriterion("num_color_resaltado_R in", values, "numColorResaltadoR");
            return this;
        }

        public Criteria andNumColorResaltadoRNotIn(List<Integer> values) {
            addCriterion("num_color_resaltado_R not in", values, "numColorResaltadoR");
            return this;
        }

        public Criteria andNumColorResaltadoRBetween(Integer value1, Integer value2) {
            addCriterion("num_color_resaltado_R between", value1, value2, "numColorResaltadoR");
            return this;
        }

        public Criteria andNumColorResaltadoRNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_resaltado_R not between", value1, value2, "numColorResaltadoR");
            return this;
        }

        public Criteria andNumColorResaltadoGIsNull() {
            addCriterion("num_color_resaltado_G is null");
            return this;
        }

        public Criteria andNumColorResaltadoGIsNotNull() {
            addCriterion("num_color_resaltado_G is not null");
            return this;
        }

        public Criteria andNumColorResaltadoGEqualTo(Integer value) {
            addCriterion("num_color_resaltado_G =", value, "numColorResaltadoG");
            return this;
        }

        public Criteria andNumColorResaltadoGNotEqualTo(Integer value) {
            addCriterion("num_color_resaltado_G <>", value, "numColorResaltadoG");
            return this;
        }

        public Criteria andNumColorResaltadoGGreaterThan(Integer value) {
            addCriterion("num_color_resaltado_G >", value, "numColorResaltadoG");
            return this;
        }

        public Criteria andNumColorResaltadoGGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_resaltado_G >=", value, "numColorResaltadoG");
            return this;
        }

        public Criteria andNumColorResaltadoGLessThan(Integer value) {
            addCriterion("num_color_resaltado_G <", value, "numColorResaltadoG");
            return this;
        }

        public Criteria andNumColorResaltadoGLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_resaltado_G <=", value, "numColorResaltadoG");
            return this;
        }

        public Criteria andNumColorResaltadoGIn(List<Integer> values) {
            addCriterion("num_color_resaltado_G in", values, "numColorResaltadoG");
            return this;
        }

        public Criteria andNumColorResaltadoGNotIn(List<Integer> values) {
            addCriterion("num_color_resaltado_G not in", values, "numColorResaltadoG");
            return this;
        }

        public Criteria andNumColorResaltadoGBetween(Integer value1, Integer value2) {
            addCriterion("num_color_resaltado_G between", value1, value2, "numColorResaltadoG");
            return this;
        }

        public Criteria andNumColorResaltadoGNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_resaltado_G not between", value1, value2, "numColorResaltadoG");
            return this;
        }

        public Criteria andNumColorResaltadoBIsNull() {
            addCriterion("num_color_resaltado_B is null");
            return this;
        }

        public Criteria andNumColorResaltadoBIsNotNull() {
            addCriterion("num_color_resaltado_B is not null");
            return this;
        }

        public Criteria andNumColorResaltadoBEqualTo(Integer value) {
            addCriterion("num_color_resaltado_B =", value, "numColorResaltadoB");
            return this;
        }

        public Criteria andNumColorResaltadoBNotEqualTo(Integer value) {
            addCriterion("num_color_resaltado_B <>", value, "numColorResaltadoB");
            return this;
        }

        public Criteria andNumColorResaltadoBGreaterThan(Integer value) {
            addCriterion("num_color_resaltado_B >", value, "numColorResaltadoB");
            return this;
        }

        public Criteria andNumColorResaltadoBGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_resaltado_B >=", value, "numColorResaltadoB");
            return this;
        }

        public Criteria andNumColorResaltadoBLessThan(Integer value) {
            addCriterion("num_color_resaltado_B <", value, "numColorResaltadoB");
            return this;
        }

        public Criteria andNumColorResaltadoBLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_resaltado_B <=", value, "numColorResaltadoB");
            return this;
        }

        public Criteria andNumColorResaltadoBIn(List<Integer> values) {
            addCriterion("num_color_resaltado_B in", values, "numColorResaltadoB");
            return this;
        }

        public Criteria andNumColorResaltadoBNotIn(List<Integer> values) {
            addCriterion("num_color_resaltado_B not in", values, "numColorResaltadoB");
            return this;
        }

        public Criteria andNumColorResaltadoBBetween(Integer value1, Integer value2) {
            addCriterion("num_color_resaltado_B between", value1, value2, "numColorResaltadoB");
            return this;
        }

        public Criteria andNumColorResaltadoBNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_resaltado_B not between", value1, value2, "numColorResaltadoB");
            return this;
        }

        public Criteria andDesTipoFuenteIsNull() {
            addCriterion("des_tipo_fuente is null");
            return this;
        }

        public Criteria andDesTipoFuenteIsNotNull() {
            addCriterion("des_tipo_fuente is not null");
            return this;
        }

        public Criteria andDesTipoFuenteEqualTo(String value) {
            addCriterion("des_tipo_fuente =", value, "desTipoFuente");
            return this;
        }

        public Criteria andDesTipoFuenteNotEqualTo(String value) {
            addCriterion("des_tipo_fuente <>", value, "desTipoFuente");
            return this;
        }

        public Criteria andDesTipoFuenteGreaterThan(String value) {
            addCriterion("des_tipo_fuente >", value, "desTipoFuente");
            return this;
        }

        public Criteria andDesTipoFuenteGreaterThanOrEqualTo(String value) {
            addCriterion("des_tipo_fuente >=", value, "desTipoFuente");
            return this;
        }

        public Criteria andDesTipoFuenteLessThan(String value) {
            addCriterion("des_tipo_fuente <", value, "desTipoFuente");
            return this;
        }

        public Criteria andDesTipoFuenteLessThanOrEqualTo(String value) {
            addCriterion("des_tipo_fuente <=", value, "desTipoFuente");
            return this;
        }

        public Criteria andDesTipoFuenteLike(String value) {
            addCriterion("des_tipo_fuente like", value, "desTipoFuente");
            return this;
        }

        public Criteria andDesTipoFuenteNotLike(String value) {
            addCriterion("des_tipo_fuente not like", value, "desTipoFuente");
            return this;
        }

        public Criteria andDesTipoFuenteIn(List<String> values) {
            addCriterion("des_tipo_fuente in", values, "desTipoFuente");
            return this;
        }

        public Criteria andDesTipoFuenteNotIn(List<String> values) {
            addCriterion("des_tipo_fuente not in", values, "desTipoFuente");
            return this;
        }

        public Criteria andDesTipoFuenteBetween(String value1, String value2) {
            addCriterion("des_tipo_fuente between", value1, value2, "desTipoFuente");
            return this;
        }

        public Criteria andDesTipoFuenteNotBetween(String value1, String value2) {
            addCriterion("des_tipo_fuente not between", value1, value2, "desTipoFuente");
            return this;
        }

        public Criteria andNumTamanioFuenteIsNull() {
            addCriterion("num_tamanio_fuente is null");
            return this;
        }

        public Criteria andNumTamanioFuenteIsNotNull() {
            addCriterion("num_tamanio_fuente is not null");
            return this;
        }

        public Criteria andNumTamanioFuenteEqualTo(Integer value) {
            addCriterion("num_tamanio_fuente =", value, "numTamanioFuente");
            return this;
        }

        public Criteria andNumTamanioFuenteNotEqualTo(Integer value) {
            addCriterion("num_tamanio_fuente <>", value, "numTamanioFuente");
            return this;
        }

        public Criteria andNumTamanioFuenteGreaterThan(Integer value) {
            addCriterion("num_tamanio_fuente >", value, "numTamanioFuente");
            return this;
        }

        public Criteria andNumTamanioFuenteGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_tamanio_fuente >=", value, "numTamanioFuente");
            return this;
        }

        public Criteria andNumTamanioFuenteLessThan(Integer value) {
            addCriterion("num_tamanio_fuente <", value, "numTamanioFuente");
            return this;
        }

        public Criteria andNumTamanioFuenteLessThanOrEqualTo(Integer value) {
            addCriterion("num_tamanio_fuente <=", value, "numTamanioFuente");
            return this;
        }

        public Criteria andNumTamanioFuenteIn(List<Integer> values) {
            addCriterion("num_tamanio_fuente in", values, "numTamanioFuente");
            return this;
        }

        public Criteria andNumTamanioFuenteNotIn(List<Integer> values) {
            addCriterion("num_tamanio_fuente not in", values, "numTamanioFuente");
            return this;
        }

        public Criteria andNumTamanioFuenteBetween(Integer value1, Integer value2) {
            addCriterion("num_tamanio_fuente between", value1, value2, "numTamanioFuente");
            return this;
        }

        public Criteria andNumTamanioFuenteNotBetween(Integer value1, Integer value2) {
            addCriterion("num_tamanio_fuente not between", value1, value2, "numTamanioFuente");
            return this;
        }

        public Criteria andNumTiempoBlinkingIsNull() {
            addCriterion("num_tiempo_blinking is null");
            return this;
        }

        public Criteria andNumTiempoBlinkingIsNotNull() {
            addCriterion("num_tiempo_blinking is not null");
            return this;
        }

        public Criteria andNumTiempoBlinkingEqualTo(Integer value) {
            addCriterion("num_tiempo_blinking =", value, "numTiempoBlinking");
            return this;
        }

        public Criteria andNumTiempoBlinkingNotEqualTo(Integer value) {
            addCriterion("num_tiempo_blinking <>", value, "numTiempoBlinking");
            return this;
        }

        public Criteria andNumTiempoBlinkingGreaterThan(Integer value) {
            addCriterion("num_tiempo_blinking >", value, "numTiempoBlinking");
            return this;
        }

        public Criteria andNumTiempoBlinkingGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_tiempo_blinking >=", value, "numTiempoBlinking");
            return this;
        }

        public Criteria andNumTiempoBlinkingLessThan(Integer value) {
            addCriterion("num_tiempo_blinking <", value, "numTiempoBlinking");
            return this;
        }

        public Criteria andNumTiempoBlinkingLessThanOrEqualTo(Integer value) {
            addCriterion("num_tiempo_blinking <=", value, "numTiempoBlinking");
            return this;
        }

        public Criteria andNumTiempoBlinkingIn(List<Integer> values) {
            addCriterion("num_tiempo_blinking in", values, "numTiempoBlinking");
            return this;
        }

        public Criteria andNumTiempoBlinkingNotIn(List<Integer> values) {
            addCriterion("num_tiempo_blinking not in", values, "numTiempoBlinking");
            return this;
        }

        public Criteria andNumTiempoBlinkingBetween(Integer value1, Integer value2) {
            addCriterion("num_tiempo_blinking between", value1, value2, "numTiempoBlinking");
            return this;
        }

        public Criteria andNumTiempoBlinkingNotBetween(Integer value1, Integer value2) {
            addCriterion("num_tiempo_blinking not between", value1, value2, "numTiempoBlinking");
            return this;
        }

        public Criteria andDesRutaSonidoLlamadoIsNull() {
            addCriterion("des_ruta_sonido_llamado is null");
            return this;
        }

        public Criteria andDesRutaSonidoLlamadoIsNotNull() {
            addCriterion("des_ruta_sonido_llamado is not null");
            return this;
        }

        public Criteria andDesRutaSonidoLlamadoEqualTo(String value) {
            addCriterion("des_ruta_sonido_llamado =", value, "desRutaSonidoLlamado");
            return this;
        }

        public Criteria andDesRutaSonidoLlamadoNotEqualTo(String value) {
            addCriterion("des_ruta_sonido_llamado <>", value, "desRutaSonidoLlamado");
            return this;
        }

        public Criteria andDesRutaSonidoLlamadoGreaterThan(String value) {
            addCriterion("des_ruta_sonido_llamado >", value, "desRutaSonidoLlamado");
            return this;
        }

        public Criteria andDesRutaSonidoLlamadoGreaterThanOrEqualTo(String value) {
            addCriterion("des_ruta_sonido_llamado >=", value, "desRutaSonidoLlamado");
            return this;
        }

        public Criteria andDesRutaSonidoLlamadoLessThan(String value) {
            addCriterion("des_ruta_sonido_llamado <", value, "desRutaSonidoLlamado");
            return this;
        }

        public Criteria andDesRutaSonidoLlamadoLessThanOrEqualTo(String value) {
            addCriterion("des_ruta_sonido_llamado <=", value, "desRutaSonidoLlamado");
            return this;
        }

        public Criteria andDesRutaSonidoLlamadoLike(String value) {
            addCriterion("des_ruta_sonido_llamado like", value, "desRutaSonidoLlamado");
            return this;
        }

        public Criteria andDesRutaSonidoLlamadoNotLike(String value) {
            addCriterion("des_ruta_sonido_llamado not like", value, "desRutaSonidoLlamado");
            return this;
        }

        public Criteria andDesRutaSonidoLlamadoIn(List<String> values) {
            addCriterion("des_ruta_sonido_llamado in", values, "desRutaSonidoLlamado");
            return this;
        }

        public Criteria andDesRutaSonidoLlamadoNotIn(List<String> values) {
            addCriterion("des_ruta_sonido_llamado not in", values, "desRutaSonidoLlamado");
            return this;
        }

        public Criteria andDesRutaSonidoLlamadoBetween(String value1, String value2) {
            addCriterion("des_ruta_sonido_llamado between", value1, value2, "desRutaSonidoLlamado");
            return this;
        }

        public Criteria andDesRutaSonidoLlamadoNotBetween(String value1, String value2) {
            addCriterion("des_ruta_sonido_llamado not between", value1, value2, "desRutaSonidoLlamado");
            return this;
        }

        public Criteria andNumColorCodigoImpresionRIsNull() {
            addCriterion("num_color_codigo_impresion_R is null");
            return this;
        }

        public Criteria andNumColorCodigoImpresionRIsNotNull() {
            addCriterion("num_color_codigo_impresion_R is not null");
            return this;
        }

        public Criteria andNumColorCodigoImpresionREqualTo(Integer value) {
            addCriterion("num_color_codigo_impresion_R =", value, "numColorCodigoImpresionR");
            return this;
        }

        public Criteria andNumColorCodigoImpresionRNotEqualTo(Integer value) {
            addCriterion("num_color_codigo_impresion_R <>", value, "numColorCodigoImpresionR");
            return this;
        }

        public Criteria andNumColorCodigoImpresionRGreaterThan(Integer value) {
            addCriterion("num_color_codigo_impresion_R >", value, "numColorCodigoImpresionR");
            return this;
        }

        public Criteria andNumColorCodigoImpresionRGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_codigo_impresion_R >=", value, "numColorCodigoImpresionR");
            return this;
        }

        public Criteria andNumColorCodigoImpresionRLessThan(Integer value) {
            addCriterion("num_color_codigo_impresion_R <", value, "numColorCodigoImpresionR");
            return this;
        }

        public Criteria andNumColorCodigoImpresionRLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_codigo_impresion_R <=", value, "numColorCodigoImpresionR");
            return this;
        }

        public Criteria andNumColorCodigoImpresionRIn(List<Integer> values) {
            addCriterion("num_color_codigo_impresion_R in", values, "numColorCodigoImpresionR");
            return this;
        }

        public Criteria andNumColorCodigoImpresionRNotIn(List<Integer> values) {
            addCriterion("num_color_codigo_impresion_R not in", values, "numColorCodigoImpresionR");
            return this;
        }

        public Criteria andNumColorCodigoImpresionRBetween(Integer value1, Integer value2) {
            addCriterion("num_color_codigo_impresion_R between", value1, value2, "numColorCodigoImpresionR");
            return this;
        }

        public Criteria andNumColorCodigoImpresionRNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_codigo_impresion_R not between", value1, value2, "numColorCodigoImpresionR");
            return this;
        }

        public Criteria andNumColorCodigoImpresionGIsNull() {
            addCriterion("num_color_codigo_impresion_G is null");
            return this;
        }

        public Criteria andNumColorCodigoImpresionGIsNotNull() {
            addCriterion("num_color_codigo_impresion_G is not null");
            return this;
        }

        public Criteria andNumColorCodigoImpresionGEqualTo(Integer value) {
            addCriterion("num_color_codigo_impresion_G =", value, "numColorCodigoImpresionG");
            return this;
        }

        public Criteria andNumColorCodigoImpresionGNotEqualTo(Integer value) {
            addCriterion("num_color_codigo_impresion_G <>", value, "numColorCodigoImpresionG");
            return this;
        }

        public Criteria andNumColorCodigoImpresionGGreaterThan(Integer value) {
            addCriterion("num_color_codigo_impresion_G >", value, "numColorCodigoImpresionG");
            return this;
        }

        public Criteria andNumColorCodigoImpresionGGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_codigo_impresion_G >=", value, "numColorCodigoImpresionG");
            return this;
        }

        public Criteria andNumColorCodigoImpresionGLessThan(Integer value) {
            addCriterion("num_color_codigo_impresion_G <", value, "numColorCodigoImpresionG");
            return this;
        }

        public Criteria andNumColorCodigoImpresionGLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_codigo_impresion_G <=", value, "numColorCodigoImpresionG");
            return this;
        }

        public Criteria andNumColorCodigoImpresionGIn(List<Integer> values) {
            addCriterion("num_color_codigo_impresion_G in", values, "numColorCodigoImpresionG");
            return this;
        }

        public Criteria andNumColorCodigoImpresionGNotIn(List<Integer> values) {
            addCriterion("num_color_codigo_impresion_G not in", values, "numColorCodigoImpresionG");
            return this;
        }

        public Criteria andNumColorCodigoImpresionGBetween(Integer value1, Integer value2) {
            addCriterion("num_color_codigo_impresion_G between", value1, value2, "numColorCodigoImpresionG");
            return this;
        }

        public Criteria andNumColorCodigoImpresionGNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_codigo_impresion_G not between", value1, value2, "numColorCodigoImpresionG");
            return this;
        }

        public Criteria andNumColorCodigoImpresionBIsNull() {
            addCriterion("num_color_codigo_impresion_B is null");
            return this;
        }

        public Criteria andNumColorCodigoImpresionBIsNotNull() {
            addCriterion("num_color_codigo_impresion_B is not null");
            return this;
        }

        public Criteria andNumColorCodigoImpresionBEqualTo(Integer value) {
            addCriterion("num_color_codigo_impresion_B =", value, "numColorCodigoImpresionB");
            return this;
        }

        public Criteria andNumColorCodigoImpresionBNotEqualTo(Integer value) {
            addCriterion("num_color_codigo_impresion_B <>", value, "numColorCodigoImpresionB");
            return this;
        }

        public Criteria andNumColorCodigoImpresionBGreaterThan(Integer value) {
            addCriterion("num_color_codigo_impresion_B >", value, "numColorCodigoImpresionB");
            return this;
        }

        public Criteria andNumColorCodigoImpresionBGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_codigo_impresion_B >=", value, "numColorCodigoImpresionB");
            return this;
        }

        public Criteria andNumColorCodigoImpresionBLessThan(Integer value) {
            addCriterion("num_color_codigo_impresion_B <", value, "numColorCodigoImpresionB");
            return this;
        }

        public Criteria andNumColorCodigoImpresionBLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_codigo_impresion_B <=", value, "numColorCodigoImpresionB");
            return this;
        }

        public Criteria andNumColorCodigoImpresionBIn(List<Integer> values) {
            addCriterion("num_color_codigo_impresion_B in", values, "numColorCodigoImpresionB");
            return this;
        }

        public Criteria andNumColorCodigoImpresionBNotIn(List<Integer> values) {
            addCriterion("num_color_codigo_impresion_B not in", values, "numColorCodigoImpresionB");
            return this;
        }

        public Criteria andNumColorCodigoImpresionBBetween(Integer value1, Integer value2) {
            addCriterion("num_color_codigo_impresion_B between", value1, value2, "numColorCodigoImpresionB");
            return this;
        }

        public Criteria andNumColorCodigoImpresionBNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_codigo_impresion_B not between", value1, value2, "numColorCodigoImpresionB");
            return this;
        }

        public Criteria andNumColorFlechaRIsNull() {
            addCriterion("num_color_flecha_R is null");
            return this;
        }

        public Criteria andNumColorFlechaRIsNotNull() {
            addCriterion("num_color_flecha_R is not null");
            return this;
        }

        public Criteria andNumColorFlechaREqualTo(Integer value) {
            addCriterion("num_color_flecha_R =", value, "numColorFlechaR");
            return this;
        }

        public Criteria andNumColorFlechaRNotEqualTo(Integer value) {
            addCriterion("num_color_flecha_R <>", value, "numColorFlechaR");
            return this;
        }

        public Criteria andNumColorFlechaRGreaterThan(Integer value) {
            addCriterion("num_color_flecha_R >", value, "numColorFlechaR");
            return this;
        }

        public Criteria andNumColorFlechaRGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_flecha_R >=", value, "numColorFlechaR");
            return this;
        }

        public Criteria andNumColorFlechaRLessThan(Integer value) {
            addCriterion("num_color_flecha_R <", value, "numColorFlechaR");
            return this;
        }

        public Criteria andNumColorFlechaRLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_flecha_R <=", value, "numColorFlechaR");
            return this;
        }

        public Criteria andNumColorFlechaRIn(List<Integer> values) {
            addCriterion("num_color_flecha_R in", values, "numColorFlechaR");
            return this;
        }

        public Criteria andNumColorFlechaRNotIn(List<Integer> values) {
            addCriterion("num_color_flecha_R not in", values, "numColorFlechaR");
            return this;
        }

        public Criteria andNumColorFlechaRBetween(Integer value1, Integer value2) {
            addCriterion("num_color_flecha_R between", value1, value2, "numColorFlechaR");
            return this;
        }

        public Criteria andNumColorFlechaRNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_flecha_R not between", value1, value2, "numColorFlechaR");
            return this;
        }

        public Criteria andNumColorFlechaGIsNull() {
            addCriterion("num_color_flecha_G is null");
            return this;
        }

        public Criteria andNumColorFlechaGIsNotNull() {
            addCriterion("num_color_flecha_G is not null");
            return this;
        }

        public Criteria andNumColorFlechaGEqualTo(Integer value) {
            addCriterion("num_color_flecha_G =", value, "numColorFlechaG");
            return this;
        }

        public Criteria andNumColorFlechaGNotEqualTo(Integer value) {
            addCriterion("num_color_flecha_G <>", value, "numColorFlechaG");
            return this;
        }

        public Criteria andNumColorFlechaGGreaterThan(Integer value) {
            addCriterion("num_color_flecha_G >", value, "numColorFlechaG");
            return this;
        }

        public Criteria andNumColorFlechaGGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_flecha_G >=", value, "numColorFlechaG");
            return this;
        }

        public Criteria andNumColorFlechaGLessThan(Integer value) {
            addCriterion("num_color_flecha_G <", value, "numColorFlechaG");
            return this;
        }

        public Criteria andNumColorFlechaGLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_flecha_G <=", value, "numColorFlechaG");
            return this;
        }

        public Criteria andNumColorFlechaGIn(List<Integer> values) {
            addCriterion("num_color_flecha_G in", values, "numColorFlechaG");
            return this;
        }

        public Criteria andNumColorFlechaGNotIn(List<Integer> values) {
            addCriterion("num_color_flecha_G not in", values, "numColorFlechaG");
            return this;
        }

        public Criteria andNumColorFlechaGBetween(Integer value1, Integer value2) {
            addCriterion("num_color_flecha_G between", value1, value2, "numColorFlechaG");
            return this;
        }

        public Criteria andNumColorFlechaGNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_flecha_G not between", value1, value2, "numColorFlechaG");
            return this;
        }

        public Criteria andNumColorFlechaBIsNull() {
            addCriterion("num_color_flecha_B is null");
            return this;
        }

        public Criteria andNumColorFlechaBIsNotNull() {
            addCriterion("num_color_flecha_B is not null");
            return this;
        }

        public Criteria andNumColorFlechaBEqualTo(Integer value) {
            addCriterion("num_color_flecha_B =", value, "numColorFlechaB");
            return this;
        }

        public Criteria andNumColorFlechaBNotEqualTo(Integer value) {
            addCriterion("num_color_flecha_B <>", value, "numColorFlechaB");
            return this;
        }

        public Criteria andNumColorFlechaBGreaterThan(Integer value) {
            addCriterion("num_color_flecha_B >", value, "numColorFlechaB");
            return this;
        }

        public Criteria andNumColorFlechaBGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_flecha_B >=", value, "numColorFlechaB");
            return this;
        }

        public Criteria andNumColorFlechaBLessThan(Integer value) {
            addCriterion("num_color_flecha_B <", value, "numColorFlechaB");
            return this;
        }

        public Criteria andNumColorFlechaBLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_flecha_B <=", value, "numColorFlechaB");
            return this;
        }

        public Criteria andNumColorFlechaBIn(List<Integer> values) {
            addCriterion("num_color_flecha_B in", values, "numColorFlechaB");
            return this;
        }

        public Criteria andNumColorFlechaBNotIn(List<Integer> values) {
            addCriterion("num_color_flecha_B not in", values, "numColorFlechaB");
            return this;
        }

        public Criteria andNumColorFlechaBBetween(Integer value1, Integer value2) {
            addCriterion("num_color_flecha_B between", value1, value2, "numColorFlechaB");
            return this;
        }

        public Criteria andNumColorFlechaBNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_flecha_B not between", value1, value2, "numColorFlechaB");
            return this;
        }

        public Criteria andNumColorVentanillaRIsNull() {
            addCriterion("num_color_ventanilla_R is null");
            return this;
        }

        public Criteria andNumColorVentanillaRIsNotNull() {
            addCriterion("num_color_ventanilla_R is not null");
            return this;
        }

        public Criteria andNumColorVentanillaREqualTo(Integer value) {
            addCriterion("num_color_ventanilla_R =", value, "numColorVentanillaR");
            return this;
        }

        public Criteria andNumColorVentanillaRNotEqualTo(Integer value) {
            addCriterion("num_color_ventanilla_R <>", value, "numColorVentanillaR");
            return this;
        }

        public Criteria andNumColorVentanillaRGreaterThan(Integer value) {
            addCriterion("num_color_ventanilla_R >", value, "numColorVentanillaR");
            return this;
        }

        public Criteria andNumColorVentanillaRGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_ventanilla_R >=", value, "numColorVentanillaR");
            return this;
        }

        public Criteria andNumColorVentanillaRLessThan(Integer value) {
            addCriterion("num_color_ventanilla_R <", value, "numColorVentanillaR");
            return this;
        }

        public Criteria andNumColorVentanillaRLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_ventanilla_R <=", value, "numColorVentanillaR");
            return this;
        }

        public Criteria andNumColorVentanillaRIn(List<Integer> values) {
            addCriterion("num_color_ventanilla_R in", values, "numColorVentanillaR");
            return this;
        }

        public Criteria andNumColorVentanillaRNotIn(List<Integer> values) {
            addCriterion("num_color_ventanilla_R not in", values, "numColorVentanillaR");
            return this;
        }

        public Criteria andNumColorVentanillaRBetween(Integer value1, Integer value2) {
            addCriterion("num_color_ventanilla_R between", value1, value2, "numColorVentanillaR");
            return this;
        }

        public Criteria andNumColorVentanillaRNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_ventanilla_R not between", value1, value2, "numColorVentanillaR");
            return this;
        }

        public Criteria andNumColorVentanillaGIsNull() {
            addCriterion("num_color_ventanilla_G is null");
            return this;
        }

        public Criteria andNumColorVentanillaGIsNotNull() {
            addCriterion("num_color_ventanilla_G is not null");
            return this;
        }

        public Criteria andNumColorVentanillaGEqualTo(Integer value) {
            addCriterion("num_color_ventanilla_G =", value, "numColorVentanillaG");
            return this;
        }

        public Criteria andNumColorVentanillaGNotEqualTo(Integer value) {
            addCriterion("num_color_ventanilla_G <>", value, "numColorVentanillaG");
            return this;
        }

        public Criteria andNumColorVentanillaGGreaterThan(Integer value) {
            addCriterion("num_color_ventanilla_G >", value, "numColorVentanillaG");
            return this;
        }

        public Criteria andNumColorVentanillaGGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_ventanilla_G >=", value, "numColorVentanillaG");
            return this;
        }

        public Criteria andNumColorVentanillaGLessThan(Integer value) {
            addCriterion("num_color_ventanilla_G <", value, "numColorVentanillaG");
            return this;
        }

        public Criteria andNumColorVentanillaGLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_ventanilla_G <=", value, "numColorVentanillaG");
            return this;
        }

        public Criteria andNumColorVentanillaGIn(List<Integer> values) {
            addCriterion("num_color_ventanilla_G in", values, "numColorVentanillaG");
            return this;
        }

        public Criteria andNumColorVentanillaGNotIn(List<Integer> values) {
            addCriterion("num_color_ventanilla_G not in", values, "numColorVentanillaG");
            return this;
        }

        public Criteria andNumColorVentanillaGBetween(Integer value1, Integer value2) {
            addCriterion("num_color_ventanilla_G between", value1, value2, "numColorVentanillaG");
            return this;
        }

        public Criteria andNumColorVentanillaGNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_ventanilla_G not between", value1, value2, "numColorVentanillaG");
            return this;
        }

        public Criteria andNumColorVentanillaBIsNull() {
            addCriterion("num_color_ventanilla_B is null");
            return this;
        }

        public Criteria andNumColorVentanillaBIsNotNull() {
            addCriterion("num_color_ventanilla_B is not null");
            return this;
        }

        public Criteria andNumColorVentanillaBEqualTo(Integer value) {
            addCriterion("num_color_ventanilla_B =", value, "numColorVentanillaB");
            return this;
        }

        public Criteria andNumColorVentanillaBNotEqualTo(Integer value) {
            addCriterion("num_color_ventanilla_B <>", value, "numColorVentanillaB");
            return this;
        }

        public Criteria andNumColorVentanillaBGreaterThan(Integer value) {
            addCriterion("num_color_ventanilla_B >", value, "numColorVentanillaB");
            return this;
        }

        public Criteria andNumColorVentanillaBGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_ventanilla_B >=", value, "numColorVentanillaB");
            return this;
        }

        public Criteria andNumColorVentanillaBLessThan(Integer value) {
            addCriterion("num_color_ventanilla_B <", value, "numColorVentanillaB");
            return this;
        }

        public Criteria andNumColorVentanillaBLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_ventanilla_B <=", value, "numColorVentanillaB");
            return this;
        }

        public Criteria andNumColorVentanillaBIn(List<Integer> values) {
            addCriterion("num_color_ventanilla_B in", values, "numColorVentanillaB");
            return this;
        }

        public Criteria andNumColorVentanillaBNotIn(List<Integer> values) {
            addCriterion("num_color_ventanilla_B not in", values, "numColorVentanillaB");
            return this;
        }

        public Criteria andNumColorVentanillaBBetween(Integer value1, Integer value2) {
            addCriterion("num_color_ventanilla_B between", value1, value2, "numColorVentanillaB");
            return this;
        }

        public Criteria andNumColorVentanillaBNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_ventanilla_B not between", value1, value2, "numColorVentanillaB");
            return this;
        }
    }
}