package pe.com.certicom.scolas.model.beans;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MarquesinaExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table MARQUESINA
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table MARQUESINA
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MARQUESINA
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public MarquesinaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MARQUESINA
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    protected MarquesinaExample(MarquesinaExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MARQUESINA
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MARQUESINA
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MARQUESINA
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MARQUESINA
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MARQUESINA
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MARQUESINA
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MARQUESINA
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MARQUESINA
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdMarquesinaIsNull() {
            addCriterion("id_marquesina is null");
            return this;
        }

        public Criteria andIdMarquesinaIsNotNull() {
            addCriterion("id_marquesina is not null");
            return this;
        }

        public Criteria andIdMarquesinaEqualTo(Integer value) {
            addCriterion("id_marquesina =", value, "idMarquesina");
            return this;
        }

        public Criteria andIdMarquesinaNotEqualTo(Integer value) {
            addCriterion("id_marquesina <>", value, "idMarquesina");
            return this;
        }

        public Criteria andIdMarquesinaGreaterThan(Integer value) {
            addCriterion("id_marquesina >", value, "idMarquesina");
            return this;
        }

        public Criteria andIdMarquesinaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_marquesina >=", value, "idMarquesina");
            return this;
        }

        public Criteria andIdMarquesinaLessThan(Integer value) {
            addCriterion("id_marquesina <", value, "idMarquesina");
            return this;
        }

        public Criteria andIdMarquesinaLessThanOrEqualTo(Integer value) {
            addCriterion("id_marquesina <=", value, "idMarquesina");
            return this;
        }

        public Criteria andIdMarquesinaIn(List<Integer> values) {
            addCriterion("id_marquesina in", values, "idMarquesina");
            return this;
        }

        public Criteria andIdMarquesinaNotIn(List<Integer> values) {
            addCriterion("id_marquesina not in", values, "idMarquesina");
            return this;
        }

        public Criteria andIdMarquesinaBetween(Integer value1, Integer value2) {
            addCriterion("id_marquesina between", value1, value2, "idMarquesina");
            return this;
        }

        public Criteria andIdMarquesinaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_marquesina not between", value1, value2, "idMarquesina");
            return this;
        }

        public Criteria andDesMensajeIsNull() {
            addCriterion("des_mensaje is null");
            return this;
        }

        public Criteria andDesMensajeIsNotNull() {
            addCriterion("des_mensaje is not null");
            return this;
        }

        public Criteria andDesMensajeEqualTo(String value) {
            addCriterion("des_mensaje =", value, "desMensaje");
            return this;
        }

        public Criteria andDesMensajeNotEqualTo(String value) {
            addCriterion("des_mensaje <>", value, "desMensaje");
            return this;
        }

        public Criteria andDesMensajeGreaterThan(String value) {
            addCriterion("des_mensaje >", value, "desMensaje");
            return this;
        }

        public Criteria andDesMensajeGreaterThanOrEqualTo(String value) {
            addCriterion("des_mensaje >=", value, "desMensaje");
            return this;
        }

        public Criteria andDesMensajeLessThan(String value) {
            addCriterion("des_mensaje <", value, "desMensaje");
            return this;
        }

        public Criteria andDesMensajeLessThanOrEqualTo(String value) {
            addCriterion("des_mensaje <=", value, "desMensaje");
            return this;
        }

        public Criteria andDesMensajeLike(String value) {
            addCriterion("des_mensaje like", value, "desMensaje");
            return this;
        }

        public Criteria andDesMensajeNotLike(String value) {
            addCriterion("des_mensaje not like", value, "desMensaje");
            return this;
        }

        public Criteria andDesMensajeIn(List<String> values) {
            addCriterion("des_mensaje in", values, "desMensaje");
            return this;
        }

        public Criteria andDesMensajeNotIn(List<String> values) {
            addCriterion("des_mensaje not in", values, "desMensaje");
            return this;
        }

        public Criteria andDesMensajeBetween(String value1, String value2) {
            addCriterion("des_mensaje between", value1, value2, "desMensaje");
            return this;
        }

        public Criteria andDesMensajeNotBetween(String value1, String value2) {
            addCriterion("des_mensaje not between", value1, value2, "desMensaje");
            return this;
        }

        public Criteria andNumColorFondoRIsNull() {
            addCriterion("num_color_fondo_R is null");
            return this;
        }

        public Criteria andNumColorFondoRIsNotNull() {
            addCriterion("num_color_fondo_R is not null");
            return this;
        }

        public Criteria andNumColorFondoREqualTo(Integer value) {
            addCriterion("num_color_fondo_R =", value, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRNotEqualTo(Integer value) {
            addCriterion("num_color_fondo_R <>", value, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRGreaterThan(Integer value) {
            addCriterion("num_color_fondo_R >", value, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_fondo_R >=", value, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRLessThan(Integer value) {
            addCriterion("num_color_fondo_R <", value, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_fondo_R <=", value, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRIn(List<Integer> values) {
            addCriterion("num_color_fondo_R in", values, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRNotIn(List<Integer> values) {
            addCriterion("num_color_fondo_R not in", values, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRBetween(Integer value1, Integer value2) {
            addCriterion("num_color_fondo_R between", value1, value2, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoRNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_fondo_R not between", value1, value2, "numColorFondoR");
            return this;
        }

        public Criteria andNumColorFondoGIsNull() {
            addCriterion("num_color_fondo_G is null");
            return this;
        }

        public Criteria andNumColorFondoGIsNotNull() {
            addCriterion("num_color_fondo_G is not null");
            return this;
        }

        public Criteria andNumColorFondoGEqualTo(Integer value) {
            addCriterion("num_color_fondo_G =", value, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGNotEqualTo(Integer value) {
            addCriterion("num_color_fondo_G <>", value, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGGreaterThan(Integer value) {
            addCriterion("num_color_fondo_G >", value, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_fondo_G >=", value, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGLessThan(Integer value) {
            addCriterion("num_color_fondo_G <", value, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_fondo_G <=", value, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGIn(List<Integer> values) {
            addCriterion("num_color_fondo_G in", values, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGNotIn(List<Integer> values) {
            addCriterion("num_color_fondo_G not in", values, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGBetween(Integer value1, Integer value2) {
            addCriterion("num_color_fondo_G between", value1, value2, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoGNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_fondo_G not between", value1, value2, "numColorFondoG");
            return this;
        }

        public Criteria andNumColorFondoBIsNull() {
            addCriterion("num_color_fondo_B is null");
            return this;
        }

        public Criteria andNumColorFondoBIsNotNull() {
            addCriterion("num_color_fondo_B is not null");
            return this;
        }

        public Criteria andNumColorFondoBEqualTo(Integer value) {
            addCriterion("num_color_fondo_B =", value, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBNotEqualTo(Integer value) {
            addCriterion("num_color_fondo_B <>", value, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBGreaterThan(Integer value) {
            addCriterion("num_color_fondo_B >", value, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_fondo_B >=", value, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBLessThan(Integer value) {
            addCriterion("num_color_fondo_B <", value, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_fondo_B <=", value, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBIn(List<Integer> values) {
            addCriterion("num_color_fondo_B in", values, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBNotIn(List<Integer> values) {
            addCriterion("num_color_fondo_B not in", values, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBBetween(Integer value1, Integer value2) {
            addCriterion("num_color_fondo_B between", value1, value2, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorFondoBNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_fondo_B not between", value1, value2, "numColorFondoB");
            return this;
        }

        public Criteria andNumColorTextoRIsNull() {
            addCriterion("num_color_texto_R is null");
            return this;
        }

        public Criteria andNumColorTextoRIsNotNull() {
            addCriterion("num_color_texto_R is not null");
            return this;
        }

        public Criteria andNumColorTextoREqualTo(Integer value) {
            addCriterion("num_color_texto_R =", value, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRNotEqualTo(Integer value) {
            addCriterion("num_color_texto_R <>", value, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRGreaterThan(Integer value) {
            addCriterion("num_color_texto_R >", value, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_texto_R >=", value, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRLessThan(Integer value) {
            addCriterion("num_color_texto_R <", value, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_texto_R <=", value, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRIn(List<Integer> values) {
            addCriterion("num_color_texto_R in", values, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRNotIn(List<Integer> values) {
            addCriterion("num_color_texto_R not in", values, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRBetween(Integer value1, Integer value2) {
            addCriterion("num_color_texto_R between", value1, value2, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoRNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_texto_R not between", value1, value2, "numColorTextoR");
            return this;
        }

        public Criteria andNumColorTextoGIsNull() {
            addCriterion("num_color_texto_G is null");
            return this;
        }

        public Criteria andNumColorTextoGIsNotNull() {
            addCriterion("num_color_texto_G is not null");
            return this;
        }

        public Criteria andNumColorTextoGEqualTo(Integer value) {
            addCriterion("num_color_texto_G =", value, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGNotEqualTo(Integer value) {
            addCriterion("num_color_texto_G <>", value, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGGreaterThan(Integer value) {
            addCriterion("num_color_texto_G >", value, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_texto_G >=", value, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGLessThan(Integer value) {
            addCriterion("num_color_texto_G <", value, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_texto_G <=", value, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGIn(List<Integer> values) {
            addCriterion("num_color_texto_G in", values, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGNotIn(List<Integer> values) {
            addCriterion("num_color_texto_G not in", values, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGBetween(Integer value1, Integer value2) {
            addCriterion("num_color_texto_G between", value1, value2, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoGNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_texto_G not between", value1, value2, "numColorTextoG");
            return this;
        }

        public Criteria andNumColorTextoBIsNull() {
            addCriterion("num_color_texto_B is null");
            return this;
        }

        public Criteria andNumColorTextoBIsNotNull() {
            addCriterion("num_color_texto_B is not null");
            return this;
        }

        public Criteria andNumColorTextoBEqualTo(Integer value) {
            addCriterion("num_color_texto_B =", value, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBNotEqualTo(Integer value) {
            addCriterion("num_color_texto_B <>", value, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBGreaterThan(Integer value) {
            addCriterion("num_color_texto_B >", value, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_color_texto_B >=", value, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBLessThan(Integer value) {
            addCriterion("num_color_texto_B <", value, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBLessThanOrEqualTo(Integer value) {
            addCriterion("num_color_texto_B <=", value, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBIn(List<Integer> values) {
            addCriterion("num_color_texto_B in", values, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBNotIn(List<Integer> values) {
            addCriterion("num_color_texto_B not in", values, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBBetween(Integer value1, Integer value2) {
            addCriterion("num_color_texto_B between", value1, value2, "numColorTextoB");
            return this;
        }

        public Criteria andNumColorTextoBNotBetween(Integer value1, Integer value2) {
            addCriterion("num_color_texto_B not between", value1, value2, "numColorTextoB");
            return this;
        }

        public Criteria andIndActivoIsNull() {
            addCriterion("ind_activo is null");
            return this;
        }

        public Criteria andIndActivoIsNotNull() {
            addCriterion("ind_activo is not null");
            return this;
        }

        public Criteria andIndActivoEqualTo(String value) {
            addCriterion("ind_activo =", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoNotEqualTo(String value) {
            addCriterion("ind_activo <>", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoGreaterThan(String value) {
            addCriterion("ind_activo >", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoGreaterThanOrEqualTo(String value) {
            addCriterion("ind_activo >=", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoLessThan(String value) {
            addCriterion("ind_activo <", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoLessThanOrEqualTo(String value) {
            addCriterion("ind_activo <=", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoLike(String value) {
            addCriterion("ind_activo like", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoNotLike(String value) {
            addCriterion("ind_activo not like", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoIn(List<String> values) {
            addCriterion("ind_activo in", values, "indActivo");
            return this;
        }

        public Criteria andIndActivoNotIn(List<String> values) {
            addCriterion("ind_activo not in", values, "indActivo");
            return this;
        }

        public Criteria andIndActivoBetween(String value1, String value2) {
            addCriterion("ind_activo between", value1, value2, "indActivo");
            return this;
        }

        public Criteria andIndActivoNotBetween(String value1, String value2) {
            addCriterion("ind_activo not between", value1, value2, "indActivo");
            return this;
        }
    }
}