package pe.com.certicom.scolas.model.beans;

public class Marquesina {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MARQUESINA.id_marquesina
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    private Integer idMarquesina;

    private Integer numVelocidad;

    private String desRutaImagen;
    private String indAlineacionImagen;

    private String desTipoFuente;
    private Integer numTamanioFuente;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MARQUESINA.des_mensaje
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    private String desMensaje;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MARQUESINA.num_color_fondo_R
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    private Integer numColorFondoR;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MARQUESINA.num_color_fondo_G
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    private Integer numColorFondoG;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MARQUESINA.num_color_fondo_B
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    private Integer numColorFondoB;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MARQUESINA.num_color_texto_R
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    private Integer numColorTextoR;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MARQUESINA.num_color_texto_G
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    private Integer numColorTextoG;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MARQUESINA.num_color_texto_B
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    private Integer numColorTextoB;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MARQUESINA.ind_activo
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    private String indActivo;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MARQUESINA.id_marquesina
     *
     * @return the value of MARQUESINA.id_marquesina
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public Integer getIdMarquesina() {
        return idMarquesina;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MARQUESINA.id_marquesina
     *
     * @param idMarquesina the value for MARQUESINA.id_marquesina
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void setIdMarquesina(Integer idMarquesina) {
        this.idMarquesina = idMarquesina;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MARQUESINA.des_mensaje
     *
     * @return the value of MARQUESINA.des_mensaje
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public String getDesMensaje() {
        return desMensaje;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MARQUESINA.des_mensaje
     *
     * @param desMensaje the value for MARQUESINA.des_mensaje
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void setDesMensaje(String desMensaje) {
        this.desMensaje = desMensaje == null ? null : desMensaje.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MARQUESINA.num_color_fondo_R
     *
     * @return the value of MARQUESINA.num_color_fondo_R
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public Integer getNumColorFondoR() {
        return numColorFondoR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MARQUESINA.num_color_fondo_R
     *
     * @param numColorFondoR the value for MARQUESINA.num_color_fondo_R
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void setNumColorFondoR(Integer numColorFondoR) {
        this.numColorFondoR = numColorFondoR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MARQUESINA.num_color_fondo_G
     *
     * @return the value of MARQUESINA.num_color_fondo_G
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public Integer getNumColorFondoG() {
        return numColorFondoG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MARQUESINA.num_color_fondo_G
     *
     * @param numColorFondoG the value for MARQUESINA.num_color_fondo_G
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void setNumColorFondoG(Integer numColorFondoG) {
        this.numColorFondoG = numColorFondoG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MARQUESINA.num_color_fondo_B
     *
     * @return the value of MARQUESINA.num_color_fondo_B
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public Integer getNumColorFondoB() {
        return numColorFondoB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MARQUESINA.num_color_fondo_B
     *
     * @param numColorFondoB the value for MARQUESINA.num_color_fondo_B
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void setNumColorFondoB(Integer numColorFondoB) {
        this.numColorFondoB = numColorFondoB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MARQUESINA.num_color_texto_R
     *
     * @return the value of MARQUESINA.num_color_texto_R
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public Integer getNumColorTextoR() {
        return numColorTextoR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MARQUESINA.num_color_texto_R
     *
     * @param numColorTextoR the value for MARQUESINA.num_color_texto_R
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void setNumColorTextoR(Integer numColorTextoR) {
        this.numColorTextoR = numColorTextoR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MARQUESINA.num_color_texto_G
     *
     * @return the value of MARQUESINA.num_color_texto_G
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public Integer getNumColorTextoG() {
        return numColorTextoG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MARQUESINA.num_color_texto_G
     *
     * @param numColorTextoG the value for MARQUESINA.num_color_texto_G
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void setNumColorTextoG(Integer numColorTextoG) {
        this.numColorTextoG = numColorTextoG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MARQUESINA.num_color_texto_B
     *
     * @return the value of MARQUESINA.num_color_texto_B
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public Integer getNumColorTextoB() {
        return numColorTextoB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MARQUESINA.num_color_texto_B
     *
     * @param numColorTextoB the value for MARQUESINA.num_color_texto_B
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void setNumColorTextoB(Integer numColorTextoB) {
        this.numColorTextoB = numColorTextoB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MARQUESINA.ind_activo
     *
     * @return the value of MARQUESINA.ind_activo
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public String getIndActivo() {
        return indActivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MARQUESINA.ind_activo
     *
     * @param indActivo the value for MARQUESINA.ind_activo
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void setIndActivo(String indActivo) {
        this.indActivo = indActivo == null ? null : indActivo.trim();
    }

    /**
     * @return the numVelocidad
     */
    public Integer getNumVelocidad() {
        return numVelocidad;
    }

    /**
     * @param numVelocidad the numVelocidad to set
     */
    public void setNumVelocidad(Integer numVelocidad) {
        this.numVelocidad = numVelocidad;
    }

    /**
     * @return the desRutaImagen
     */
    public String getDesRutaImagen() {
        return desRutaImagen;
    }

    /**
     * @param desRutaImagen the desRutaImagen to set
     */
    public void setDesRutaImagen(String desRutaImagen) {
        this.desRutaImagen = desRutaImagen;
    }

    /**
     * @return the indAlineacionImagen
     */
    public String getIndAlineacionImagen() {
        return indAlineacionImagen;
    }

    /**
     * @param indAlineacionImagen the indAlineacionImagen to set
     */
    public void setIndAlineacionImagen(String indAlineacionImagen) {
        this.indAlineacionImagen = indAlineacionImagen;
    }

    /**
     * @return the desTipoFuente
     */
    public String getDesTipoFuente() {
        return desTipoFuente;
    }

    /**
     * @param desTipoFuente the desTipoFuente to set
     */
    public void setDesTipoFuente(String desTipoFuente) {
        this.desTipoFuente = desTipoFuente;
    }

    /**
     * @return the numTamanioFuente
     */
    public Integer getNumTamanioFuente() {
        return numTamanioFuente;
    }

    /**
     * @param numTamanioFuente the numTamanioFuente to set
     */
    public void setNumTamanioFuente(Integer numTamanioFuente) {
        this.numTamanioFuente = numTamanioFuente;
    }

}