package pe.com.certicom.scolas.model.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.com.certicom.scolas.model.beans.GrillaLlamados;
import pe.com.certicom.scolas.model.beans.GrillaLlamadosExample;

public class GrillaLlamadosDAOImpl extends SqlMapClientDaoSupport implements GrillaLlamadosDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    public GrillaLlamadosDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    public int countByExample(GrillaLlamadosExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("GRILLA_LLAMADOS.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    public int deleteByExample(GrillaLlamadosExample example) {
        int rows = getSqlMapClientTemplate().delete("GRILLA_LLAMADOS.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    public int deleteByPrimaryKey(Integer idGrillaLlamados) {
        GrillaLlamados key = new GrillaLlamados();
        key.setIdGrillaLlamados(idGrillaLlamados);
        int rows = getSqlMapClientTemplate().delete("GRILLA_LLAMADOS.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    public void insert(GrillaLlamados record) {
        getSqlMapClientTemplate().insert("GRILLA_LLAMADOS.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    public void insertSelective(GrillaLlamados record) {
        getSqlMapClientTemplate().insert("GRILLA_LLAMADOS.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    @SuppressWarnings("unchecked")
    public List<GrillaLlamados> selectByExample(GrillaLlamadosExample example) {
        List<GrillaLlamados> list = getSqlMapClientTemplate().queryForList("GRILLA_LLAMADOS.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    public GrillaLlamados selectByPrimaryKey(Integer idGrillaLlamados) {
        GrillaLlamados key = new GrillaLlamados();
        key.setIdGrillaLlamados(idGrillaLlamados);
        GrillaLlamados record = (GrillaLlamados) getSqlMapClientTemplate().queryForObject("GRILLA_LLAMADOS.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    public int updateByExampleSelective(GrillaLlamados record, GrillaLlamadosExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("GRILLA_LLAMADOS.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    public int updateByExample(GrillaLlamados record, GrillaLlamadosExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("GRILLA_LLAMADOS.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    public int updateByPrimaryKeySelective(GrillaLlamados record) {
        int rows = getSqlMapClientTemplate().update("GRILLA_LLAMADOS.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    public int updateByPrimaryKey(GrillaLlamados record) {
        int rows = getSqlMapClientTemplate().update("GRILLA_LLAMADOS.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    public GrillaLlamados getConfiguracionGrilla() {
        return (GrillaLlamados) getSqlMapClientTemplate().queryForObject("GRILLA_LLAMADOS.getConfiguracionGrilla");
    }

    public GrillaLlamados getConfiguracionGrilla(Integer idConfiguracion) {
        Map<String,Integer> parametros = new HashMap<String,Integer>();
        parametros.put("idConfiguracion",idConfiguracion);
        return (GrillaLlamados) getSqlMapClientTemplate().queryForObject("GRILLA_LLAMADOS.getConfiguracionGrilla",parametros);
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table GRILLA_LLAMADOS
     *
     * @ibatorgenerated Sun Dec 11 22:14:54 COT 2011
     */
    private static class UpdateByExampleParms extends GrillaLlamadosExample {
        private Object record;

        public UpdateByExampleParms(Object record, GrillaLlamadosExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}