package pe.com.certicom.scolas.model.beans;

public class ConfiguracionMonitorKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.id_lista_videos
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer idListaVideos;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.id_lista_marquesinas
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer idListaMarquesinas;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column configuracion_emisor_llamados.id_grilla_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    private Integer idGrillaLlamados;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.id_lista_videos
     *
     * @return the value of configuracion_emisor_llamados.id_lista_videos
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getIdListaVideos() {
        return idListaVideos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.id_lista_videos
     *
     * @param idListaVideos the value for configuracion_emisor_llamados.id_lista_videos
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setIdListaVideos(Integer idListaVideos) {
        this.idListaVideos = idListaVideos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.id_lista_marquesinas
     *
     * @return the value of configuracion_emisor_llamados.id_lista_marquesinas
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getIdListaMarquesinas() {
        return idListaMarquesinas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.id_lista_marquesinas
     *
     * @param idListaMarquesinas the value for configuracion_emisor_llamados.id_lista_marquesinas
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setIdListaMarquesinas(Integer idListaMarquesinas) {
        this.idListaMarquesinas = idListaMarquesinas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column configuracion_emisor_llamados.id_grilla_llamados
     *
     * @return the value of configuracion_emisor_llamados.id_grilla_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Integer getIdGrillaLlamados() {
        return idGrillaLlamados;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column configuracion_emisor_llamados.id_grilla_llamados
     *
     * @param idGrillaLlamados the value for configuracion_emisor_llamados.id_grilla_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setIdGrillaLlamados(Integer idGrillaLlamados) {
        this.idGrillaLlamados = idGrillaLlamados;
    }
}