package pe.com.certicom.scolas.model.beans;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ConfiguracionMonitorExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public ConfiguracionMonitorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    protected ConfiguracionMonitorExample(ConfiguracionMonitorExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table configuracion_emisor_llamados
     *
     * @ibatorgenerated Wed Dec 14 16:15:54 COT 2011
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdListaVideosIsNull() {
            addCriterion("id_lista_videos is null");
            return this;
        }

        public Criteria andIdListaVideosIsNotNull() {
            addCriterion("id_lista_videos is not null");
            return this;
        }

        public Criteria andIdListaVideosEqualTo(Integer value) {
            addCriterion("id_lista_videos =", value, "idListaVideos");
            return this;
        }

        public Criteria andIdListaVideosNotEqualTo(Integer value) {
            addCriterion("id_lista_videos <>", value, "idListaVideos");
            return this;
        }

        public Criteria andIdListaVideosGreaterThan(Integer value) {
            addCriterion("id_lista_videos >", value, "idListaVideos");
            return this;
        }

        public Criteria andIdListaVideosGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_lista_videos >=", value, "idListaVideos");
            return this;
        }

        public Criteria andIdListaVideosLessThan(Integer value) {
            addCriterion("id_lista_videos <", value, "idListaVideos");
            return this;
        }

        public Criteria andIdListaVideosLessThanOrEqualTo(Integer value) {
            addCriterion("id_lista_videos <=", value, "idListaVideos");
            return this;
        }

        public Criteria andIdListaVideosIn(List<Integer> values) {
            addCriterion("id_lista_videos in", values, "idListaVideos");
            return this;
        }

        public Criteria andIdListaVideosNotIn(List<Integer> values) {
            addCriterion("id_lista_videos not in", values, "idListaVideos");
            return this;
        }

        public Criteria andIdListaVideosBetween(Integer value1, Integer value2) {
            addCriterion("id_lista_videos between", value1, value2, "idListaVideos");
            return this;
        }

        public Criteria andIdListaVideosNotBetween(Integer value1, Integer value2) {
            addCriterion("id_lista_videos not between", value1, value2, "idListaVideos");
            return this;
        }

        public Criteria andIdListaMarquesinasIsNull() {
            addCriterion("id_lista_marquesinas is null");
            return this;
        }

        public Criteria andIdListaMarquesinasIsNotNull() {
            addCriterion("id_lista_marquesinas is not null");
            return this;
        }

        public Criteria andIdListaMarquesinasEqualTo(Integer value) {
            addCriterion("id_lista_marquesinas =", value, "idListaMarquesinas");
            return this;
        }

        public Criteria andIdListaMarquesinasNotEqualTo(Integer value) {
            addCriterion("id_lista_marquesinas <>", value, "idListaMarquesinas");
            return this;
        }

        public Criteria andIdListaMarquesinasGreaterThan(Integer value) {
            addCriterion("id_lista_marquesinas >", value, "idListaMarquesinas");
            return this;
        }

        public Criteria andIdListaMarquesinasGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_lista_marquesinas >=", value, "idListaMarquesinas");
            return this;
        }

        public Criteria andIdListaMarquesinasLessThan(Integer value) {
            addCriterion("id_lista_marquesinas <", value, "idListaMarquesinas");
            return this;
        }

        public Criteria andIdListaMarquesinasLessThanOrEqualTo(Integer value) {
            addCriterion("id_lista_marquesinas <=", value, "idListaMarquesinas");
            return this;
        }

        public Criteria andIdListaMarquesinasIn(List<Integer> values) {
            addCriterion("id_lista_marquesinas in", values, "idListaMarquesinas");
            return this;
        }

        public Criteria andIdListaMarquesinasNotIn(List<Integer> values) {
            addCriterion("id_lista_marquesinas not in", values, "idListaMarquesinas");
            return this;
        }

        public Criteria andIdListaMarquesinasBetween(Integer value1, Integer value2) {
            addCriterion("id_lista_marquesinas between", value1, value2, "idListaMarquesinas");
            return this;
        }

        public Criteria andIdListaMarquesinasNotBetween(Integer value1, Integer value2) {
            addCriterion("id_lista_marquesinas not between", value1, value2, "idListaMarquesinas");
            return this;
        }

        public Criteria andIdGrillaLlamadosIsNull() {
            addCriterion("id_grilla_llamados is null");
            return this;
        }

        public Criteria andIdGrillaLlamadosIsNotNull() {
            addCriterion("id_grilla_llamados is not null");
            return this;
        }

        public Criteria andIdGrillaLlamadosEqualTo(Integer value) {
            addCriterion("id_grilla_llamados =", value, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosNotEqualTo(Integer value) {
            addCriterion("id_grilla_llamados <>", value, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosGreaterThan(Integer value) {
            addCriterion("id_grilla_llamados >", value, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_grilla_llamados >=", value, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosLessThan(Integer value) {
            addCriterion("id_grilla_llamados <", value, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosLessThanOrEqualTo(Integer value) {
            addCriterion("id_grilla_llamados <=", value, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosIn(List<Integer> values) {
            addCriterion("id_grilla_llamados in", values, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosNotIn(List<Integer> values) {
            addCriterion("id_grilla_llamados not in", values, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosBetween(Integer value1, Integer value2) {
            addCriterion("id_grilla_llamados between", value1, value2, "idGrillaLlamados");
            return this;
        }

        public Criteria andIdGrillaLlamadosNotBetween(Integer value1, Integer value2) {
            addCriterion("id_grilla_llamados not between", value1, value2, "idGrillaLlamados");
            return this;
        }

        public Criteria andNumPosAppXIsNull() {
            addCriterion("num_pos_app_x is null");
            return this;
        }

        public Criteria andNumPosAppXIsNotNull() {
            addCriterion("num_pos_app_x is not null");
            return this;
        }

        public Criteria andNumPosAppXEqualTo(Integer value) {
            addCriterion("num_pos_app_x =", value, "numPosAppX");
            return this;
        }

        public Criteria andNumPosAppXNotEqualTo(Integer value) {
            addCriterion("num_pos_app_x <>", value, "numPosAppX");
            return this;
        }

        public Criteria andNumPosAppXGreaterThan(Integer value) {
            addCriterion("num_pos_app_x >", value, "numPosAppX");
            return this;
        }

        public Criteria andNumPosAppXGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_pos_app_x >=", value, "numPosAppX");
            return this;
        }

        public Criteria andNumPosAppXLessThan(Integer value) {
            addCriterion("num_pos_app_x <", value, "numPosAppX");
            return this;
        }

        public Criteria andNumPosAppXLessThanOrEqualTo(Integer value) {
            addCriterion("num_pos_app_x <=", value, "numPosAppX");
            return this;
        }

        public Criteria andNumPosAppXIn(List<Integer> values) {
            addCriterion("num_pos_app_x in", values, "numPosAppX");
            return this;
        }

        public Criteria andNumPosAppXNotIn(List<Integer> values) {
            addCriterion("num_pos_app_x not in", values, "numPosAppX");
            return this;
        }

        public Criteria andNumPosAppXBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_app_x between", value1, value2, "numPosAppX");
            return this;
        }

        public Criteria andNumPosAppXNotBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_app_x not between", value1, value2, "numPosAppX");
            return this;
        }

        public Criteria andNumPosAppYIsNull() {
            addCriterion("num_pos_app_y is null");
            return this;
        }

        public Criteria andNumPosAppYIsNotNull() {
            addCriterion("num_pos_app_y is not null");
            return this;
        }

        public Criteria andNumPosAppYEqualTo(Integer value) {
            addCriterion("num_pos_app_y =", value, "numPosAppY");
            return this;
        }

        public Criteria andNumPosAppYNotEqualTo(Integer value) {
            addCriterion("num_pos_app_y <>", value, "numPosAppY");
            return this;
        }

        public Criteria andNumPosAppYGreaterThan(Integer value) {
            addCriterion("num_pos_app_y >", value, "numPosAppY");
            return this;
        }

        public Criteria andNumPosAppYGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_pos_app_y >=", value, "numPosAppY");
            return this;
        }

        public Criteria andNumPosAppYLessThan(Integer value) {
            addCriterion("num_pos_app_y <", value, "numPosAppY");
            return this;
        }

        public Criteria andNumPosAppYLessThanOrEqualTo(Integer value) {
            addCriterion("num_pos_app_y <=", value, "numPosAppY");
            return this;
        }

        public Criteria andNumPosAppYIn(List<Integer> values) {
            addCriterion("num_pos_app_y in", values, "numPosAppY");
            return this;
        }

        public Criteria andNumPosAppYNotIn(List<Integer> values) {
            addCriterion("num_pos_app_y not in", values, "numPosAppY");
            return this;
        }

        public Criteria andNumPosAppYBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_app_y between", value1, value2, "numPosAppY");
            return this;
        }

        public Criteria andNumPosAppYNotBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_app_y not between", value1, value2, "numPosAppY");
            return this;
        }

        public Criteria andNumDimAppXIsNull() {
            addCriterion("num_dim_app_x is null");
            return this;
        }

        public Criteria andNumDimAppXIsNotNull() {
            addCriterion("num_dim_app_x is not null");
            return this;
        }

        public Criteria andNumDimAppXEqualTo(Integer value) {
            addCriterion("num_dim_app_x =", value, "numDimAppX");
            return this;
        }

        public Criteria andNumDimAppXNotEqualTo(Integer value) {
            addCriterion("num_dim_app_x <>", value, "numDimAppX");
            return this;
        }

        public Criteria andNumDimAppXGreaterThan(Integer value) {
            addCriterion("num_dim_app_x >", value, "numDimAppX");
            return this;
        }

        public Criteria andNumDimAppXGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_dim_app_x >=", value, "numDimAppX");
            return this;
        }

        public Criteria andNumDimAppXLessThan(Integer value) {
            addCriterion("num_dim_app_x <", value, "numDimAppX");
            return this;
        }

        public Criteria andNumDimAppXLessThanOrEqualTo(Integer value) {
            addCriterion("num_dim_app_x <=", value, "numDimAppX");
            return this;
        }

        public Criteria andNumDimAppXIn(List<Integer> values) {
            addCriterion("num_dim_app_x in", values, "numDimAppX");
            return this;
        }

        public Criteria andNumDimAppXNotIn(List<Integer> values) {
            addCriterion("num_dim_app_x not in", values, "numDimAppX");
            return this;
        }

        public Criteria andNumDimAppXBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_app_x between", value1, value2, "numDimAppX");
            return this;
        }

        public Criteria andNumDimAppXNotBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_app_x not between", value1, value2, "numDimAppX");
            return this;
        }

        public Criteria andNumDimAppYIsNull() {
            addCriterion("num_dim_app_y is null");
            return this;
        }

        public Criteria andNumDimAppYIsNotNull() {
            addCriterion("num_dim_app_y is not null");
            return this;
        }

        public Criteria andNumDimAppYEqualTo(Integer value) {
            addCriterion("num_dim_app_y =", value, "numDimAppY");
            return this;
        }

        public Criteria andNumDimAppYNotEqualTo(Integer value) {
            addCriterion("num_dim_app_y <>", value, "numDimAppY");
            return this;
        }

        public Criteria andNumDimAppYGreaterThan(Integer value) {
            addCriterion("num_dim_app_y >", value, "numDimAppY");
            return this;
        }

        public Criteria andNumDimAppYGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_dim_app_y >=", value, "numDimAppY");
            return this;
        }

        public Criteria andNumDimAppYLessThan(Integer value) {
            addCriterion("num_dim_app_y <", value, "numDimAppY");
            return this;
        }

        public Criteria andNumDimAppYLessThanOrEqualTo(Integer value) {
            addCriterion("num_dim_app_y <=", value, "numDimAppY");
            return this;
        }

        public Criteria andNumDimAppYIn(List<Integer> values) {
            addCriterion("num_dim_app_y in", values, "numDimAppY");
            return this;
        }

        public Criteria andNumDimAppYNotIn(List<Integer> values) {
            addCriterion("num_dim_app_y not in", values, "numDimAppY");
            return this;
        }

        public Criteria andNumDimAppYBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_app_y between", value1, value2, "numDimAppY");
            return this;
        }

        public Criteria andNumDimAppYNotBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_app_y not between", value1, value2, "numDimAppY");
            return this;
        }

        public Criteria andNumPosVideoXIsNull() {
            addCriterion("num_pos_video_x is null");
            return this;
        }

        public Criteria andNumPosVideoXIsNotNull() {
            addCriterion("num_pos_video_x is not null");
            return this;
        }

        public Criteria andNumPosVideoXEqualTo(Integer value) {
            addCriterion("num_pos_video_x =", value, "numPosVideoX");
            return this;
        }

        public Criteria andNumPosVideoXNotEqualTo(Integer value) {
            addCriterion("num_pos_video_x <>", value, "numPosVideoX");
            return this;
        }

        public Criteria andNumPosVideoXGreaterThan(Integer value) {
            addCriterion("num_pos_video_x >", value, "numPosVideoX");
            return this;
        }

        public Criteria andNumPosVideoXGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_pos_video_x >=", value, "numPosVideoX");
            return this;
        }

        public Criteria andNumPosVideoXLessThan(Integer value) {
            addCriterion("num_pos_video_x <", value, "numPosVideoX");
            return this;
        }

        public Criteria andNumPosVideoXLessThanOrEqualTo(Integer value) {
            addCriterion("num_pos_video_x <=", value, "numPosVideoX");
            return this;
        }

        public Criteria andNumPosVideoXIn(List<Integer> values) {
            addCriterion("num_pos_video_x in", values, "numPosVideoX");
            return this;
        }

        public Criteria andNumPosVideoXNotIn(List<Integer> values) {
            addCriterion("num_pos_video_x not in", values, "numPosVideoX");
            return this;
        }

        public Criteria andNumPosVideoXBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_video_x between", value1, value2, "numPosVideoX");
            return this;
        }

        public Criteria andNumPosVideoXNotBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_video_x not between", value1, value2, "numPosVideoX");
            return this;
        }

        public Criteria andNumPosVideoYIsNull() {
            addCriterion("num_pos_video_y is null");
            return this;
        }

        public Criteria andNumPosVideoYIsNotNull() {
            addCriterion("num_pos_video_y is not null");
            return this;
        }

        public Criteria andNumPosVideoYEqualTo(Integer value) {
            addCriterion("num_pos_video_y =", value, "numPosVideoY");
            return this;
        }

        public Criteria andNumPosVideoYNotEqualTo(Integer value) {
            addCriterion("num_pos_video_y <>", value, "numPosVideoY");
            return this;
        }

        public Criteria andNumPosVideoYGreaterThan(Integer value) {
            addCriterion("num_pos_video_y >", value, "numPosVideoY");
            return this;
        }

        public Criteria andNumPosVideoYGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_pos_video_y >=", value, "numPosVideoY");
            return this;
        }

        public Criteria andNumPosVideoYLessThan(Integer value) {
            addCriterion("num_pos_video_y <", value, "numPosVideoY");
            return this;
        }

        public Criteria andNumPosVideoYLessThanOrEqualTo(Integer value) {
            addCriterion("num_pos_video_y <=", value, "numPosVideoY");
            return this;
        }

        public Criteria andNumPosVideoYIn(List<Integer> values) {
            addCriterion("num_pos_video_y in", values, "numPosVideoY");
            return this;
        }

        public Criteria andNumPosVideoYNotIn(List<Integer> values) {
            addCriterion("num_pos_video_y not in", values, "numPosVideoY");
            return this;
        }

        public Criteria andNumPosVideoYBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_video_y between", value1, value2, "numPosVideoY");
            return this;
        }

        public Criteria andNumPosVideoYNotBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_video_y not between", value1, value2, "numPosVideoY");
            return this;
        }

        public Criteria andNumDimVideoXIsNull() {
            addCriterion("num_dim_video_x is null");
            return this;
        }

        public Criteria andNumDimVideoXIsNotNull() {
            addCriterion("num_dim_video_x is not null");
            return this;
        }

        public Criteria andNumDimVideoXEqualTo(Integer value) {
            addCriterion("num_dim_video_x =", value, "numDimVideoX");
            return this;
        }

        public Criteria andNumDimVideoXNotEqualTo(Integer value) {
            addCriterion("num_dim_video_x <>", value, "numDimVideoX");
            return this;
        }

        public Criteria andNumDimVideoXGreaterThan(Integer value) {
            addCriterion("num_dim_video_x >", value, "numDimVideoX");
            return this;
        }

        public Criteria andNumDimVideoXGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_dim_video_x >=", value, "numDimVideoX");
            return this;
        }

        public Criteria andNumDimVideoXLessThan(Integer value) {
            addCriterion("num_dim_video_x <", value, "numDimVideoX");
            return this;
        }

        public Criteria andNumDimVideoXLessThanOrEqualTo(Integer value) {
            addCriterion("num_dim_video_x <=", value, "numDimVideoX");
            return this;
        }

        public Criteria andNumDimVideoXIn(List<Integer> values) {
            addCriterion("num_dim_video_x in", values, "numDimVideoX");
            return this;
        }

        public Criteria andNumDimVideoXNotIn(List<Integer> values) {
            addCriterion("num_dim_video_x not in", values, "numDimVideoX");
            return this;
        }

        public Criteria andNumDimVideoXBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_video_x between", value1, value2, "numDimVideoX");
            return this;
        }

        public Criteria andNumDimVideoXNotBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_video_x not between", value1, value2, "numDimVideoX");
            return this;
        }

        public Criteria andNumDimVideoYIsNull() {
            addCriterion("num_dim_video_y is null");
            return this;
        }

        public Criteria andNumDimVideoYIsNotNull() {
            addCriterion("num_dim_video_y is not null");
            return this;
        }

        public Criteria andNumDimVideoYEqualTo(Integer value) {
            addCriterion("num_dim_video_y =", value, "numDimVideoY");
            return this;
        }

        public Criteria andNumDimVideoYNotEqualTo(Integer value) {
            addCriterion("num_dim_video_y <>", value, "numDimVideoY");
            return this;
        }

        public Criteria andNumDimVideoYGreaterThan(Integer value) {
            addCriterion("num_dim_video_y >", value, "numDimVideoY");
            return this;
        }

        public Criteria andNumDimVideoYGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_dim_video_y >=", value, "numDimVideoY");
            return this;
        }

        public Criteria andNumDimVideoYLessThan(Integer value) {
            addCriterion("num_dim_video_y <", value, "numDimVideoY");
            return this;
        }

        public Criteria andNumDimVideoYLessThanOrEqualTo(Integer value) {
            addCriterion("num_dim_video_y <=", value, "numDimVideoY");
            return this;
        }

        public Criteria andNumDimVideoYIn(List<Integer> values) {
            addCriterion("num_dim_video_y in", values, "numDimVideoY");
            return this;
        }

        public Criteria andNumDimVideoYNotIn(List<Integer> values) {
            addCriterion("num_dim_video_y not in", values, "numDimVideoY");
            return this;
        }

        public Criteria andNumDimVideoYBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_video_y between", value1, value2, "numDimVideoY");
            return this;
        }

        public Criteria andNumDimVideoYNotBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_video_y not between", value1, value2, "numDimVideoY");
            return this;
        }

        public Criteria andNumPosMarquesinaXIsNull() {
            addCriterion("num_pos_marquesina_x is null");
            return this;
        }

        public Criteria andNumPosMarquesinaXIsNotNull() {
            addCriterion("num_pos_marquesina_x is not null");
            return this;
        }

        public Criteria andNumPosMarquesinaXEqualTo(Integer value) {
            addCriterion("num_pos_marquesina_x =", value, "numPosMarquesinaX");
            return this;
        }

        public Criteria andNumPosMarquesinaXNotEqualTo(Integer value) {
            addCriterion("num_pos_marquesina_x <>", value, "numPosMarquesinaX");
            return this;
        }

        public Criteria andNumPosMarquesinaXGreaterThan(Integer value) {
            addCriterion("num_pos_marquesina_x >", value, "numPosMarquesinaX");
            return this;
        }

        public Criteria andNumPosMarquesinaXGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_pos_marquesina_x >=", value, "numPosMarquesinaX");
            return this;
        }

        public Criteria andNumPosMarquesinaXLessThan(Integer value) {
            addCriterion("num_pos_marquesina_x <", value, "numPosMarquesinaX");
            return this;
        }

        public Criteria andNumPosMarquesinaXLessThanOrEqualTo(Integer value) {
            addCriterion("num_pos_marquesina_x <=", value, "numPosMarquesinaX");
            return this;
        }

        public Criteria andNumPosMarquesinaXIn(List<Integer> values) {
            addCriterion("num_pos_marquesina_x in", values, "numPosMarquesinaX");
            return this;
        }

        public Criteria andNumPosMarquesinaXNotIn(List<Integer> values) {
            addCriterion("num_pos_marquesina_x not in", values, "numPosMarquesinaX");
            return this;
        }

        public Criteria andNumPosMarquesinaXBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_marquesina_x between", value1, value2, "numPosMarquesinaX");
            return this;
        }

        public Criteria andNumPosMarquesinaXNotBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_marquesina_x not between", value1, value2, "numPosMarquesinaX");
            return this;
        }

        public Criteria andNumPosMarquesinaYIsNull() {
            addCriterion("num_pos_marquesina_y is null");
            return this;
        }

        public Criteria andNumPosMarquesinaYIsNotNull() {
            addCriterion("num_pos_marquesina_y is not null");
            return this;
        }

        public Criteria andNumPosMarquesinaYEqualTo(Integer value) {
            addCriterion("num_pos_marquesina_y =", value, "numPosMarquesinaY");
            return this;
        }

        public Criteria andNumPosMarquesinaYNotEqualTo(Integer value) {
            addCriterion("num_pos_marquesina_y <>", value, "numPosMarquesinaY");
            return this;
        }

        public Criteria andNumPosMarquesinaYGreaterThan(Integer value) {
            addCriterion("num_pos_marquesina_y >", value, "numPosMarquesinaY");
            return this;
        }

        public Criteria andNumPosMarquesinaYGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_pos_marquesina_y >=", value, "numPosMarquesinaY");
            return this;
        }

        public Criteria andNumPosMarquesinaYLessThan(Integer value) {
            addCriterion("num_pos_marquesina_y <", value, "numPosMarquesinaY");
            return this;
        }

        public Criteria andNumPosMarquesinaYLessThanOrEqualTo(Integer value) {
            addCriterion("num_pos_marquesina_y <=", value, "numPosMarquesinaY");
            return this;
        }

        public Criteria andNumPosMarquesinaYIn(List<Integer> values) {
            addCriterion("num_pos_marquesina_y in", values, "numPosMarquesinaY");
            return this;
        }

        public Criteria andNumPosMarquesinaYNotIn(List<Integer> values) {
            addCriterion("num_pos_marquesina_y not in", values, "numPosMarquesinaY");
            return this;
        }

        public Criteria andNumPosMarquesinaYBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_marquesina_y between", value1, value2, "numPosMarquesinaY");
            return this;
        }

        public Criteria andNumPosMarquesinaYNotBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_marquesina_y not between", value1, value2, "numPosMarquesinaY");
            return this;
        }

        public Criteria andNumDimMarquesinaXIsNull() {
            addCriterion("num_dim_marquesina_x is null");
            return this;
        }

        public Criteria andNumDimMarquesinaXIsNotNull() {
            addCriterion("num_dim_marquesina_x is not null");
            return this;
        }

        public Criteria andNumDimMarquesinaXEqualTo(Integer value) {
            addCriterion("num_dim_marquesina_x =", value, "numDimMarquesinaX");
            return this;
        }

        public Criteria andNumDimMarquesinaXNotEqualTo(Integer value) {
            addCriterion("num_dim_marquesina_x <>", value, "numDimMarquesinaX");
            return this;
        }

        public Criteria andNumDimMarquesinaXGreaterThan(Integer value) {
            addCriterion("num_dim_marquesina_x >", value, "numDimMarquesinaX");
            return this;
        }

        public Criteria andNumDimMarquesinaXGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_dim_marquesina_x >=", value, "numDimMarquesinaX");
            return this;
        }

        public Criteria andNumDimMarquesinaXLessThan(Integer value) {
            addCriterion("num_dim_marquesina_x <", value, "numDimMarquesinaX");
            return this;
        }

        public Criteria andNumDimMarquesinaXLessThanOrEqualTo(Integer value) {
            addCriterion("num_dim_marquesina_x <=", value, "numDimMarquesinaX");
            return this;
        }

        public Criteria andNumDimMarquesinaXIn(List<Integer> values) {
            addCriterion("num_dim_marquesina_x in", values, "numDimMarquesinaX");
            return this;
        }

        public Criteria andNumDimMarquesinaXNotIn(List<Integer> values) {
            addCriterion("num_dim_marquesina_x not in", values, "numDimMarquesinaX");
            return this;
        }

        public Criteria andNumDimMarquesinaXBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_marquesina_x between", value1, value2, "numDimMarquesinaX");
            return this;
        }

        public Criteria andNumDimMarquesinaXNotBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_marquesina_x not between", value1, value2, "numDimMarquesinaX");
            return this;
        }

        public Criteria andNumDimMarquesinaYIsNull() {
            addCriterion("num_dim_marquesina_y is null");
            return this;
        }

        public Criteria andNumDimMarquesinaYIsNotNull() {
            addCriterion("num_dim_marquesina_y is not null");
            return this;
        }

        public Criteria andNumDimMarquesinaYEqualTo(Integer value) {
            addCriterion("num_dim_marquesina_y =", value, "numDimMarquesinaY");
            return this;
        }

        public Criteria andNumDimMarquesinaYNotEqualTo(Integer value) {
            addCriterion("num_dim_marquesina_y <>", value, "numDimMarquesinaY");
            return this;
        }

        public Criteria andNumDimMarquesinaYGreaterThan(Integer value) {
            addCriterion("num_dim_marquesina_y >", value, "numDimMarquesinaY");
            return this;
        }

        public Criteria andNumDimMarquesinaYGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_dim_marquesina_y >=", value, "numDimMarquesinaY");
            return this;
        }

        public Criteria andNumDimMarquesinaYLessThan(Integer value) {
            addCriterion("num_dim_marquesina_y <", value, "numDimMarquesinaY");
            return this;
        }

        public Criteria andNumDimMarquesinaYLessThanOrEqualTo(Integer value) {
            addCriterion("num_dim_marquesina_y <=", value, "numDimMarquesinaY");
            return this;
        }

        public Criteria andNumDimMarquesinaYIn(List<Integer> values) {
            addCriterion("num_dim_marquesina_y in", values, "numDimMarquesinaY");
            return this;
        }

        public Criteria andNumDimMarquesinaYNotIn(List<Integer> values) {
            addCriterion("num_dim_marquesina_y not in", values, "numDimMarquesinaY");
            return this;
        }

        public Criteria andNumDimMarquesinaYBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_marquesina_y between", value1, value2, "numDimMarquesinaY");
            return this;
        }

        public Criteria andNumDimMarquesinaYNotBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_marquesina_y not between", value1, value2, "numDimMarquesinaY");
            return this;
        }

        public Criteria andNumPosGrillaXIsNull() {
            addCriterion("num_pos_grilla_x is null");
            return this;
        }

        public Criteria andNumPosGrillaXIsNotNull() {
            addCriterion("num_pos_grilla_x is not null");
            return this;
        }

        public Criteria andNumPosGrillaXEqualTo(Integer value) {
            addCriterion("num_pos_grilla_x =", value, "numPosGrillaX");
            return this;
        }

        public Criteria andNumPosGrillaXNotEqualTo(Integer value) {
            addCriterion("num_pos_grilla_x <>", value, "numPosGrillaX");
            return this;
        }

        public Criteria andNumPosGrillaXGreaterThan(Integer value) {
            addCriterion("num_pos_grilla_x >", value, "numPosGrillaX");
            return this;
        }

        public Criteria andNumPosGrillaXGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_pos_grilla_x >=", value, "numPosGrillaX");
            return this;
        }

        public Criteria andNumPosGrillaXLessThan(Integer value) {
            addCriterion("num_pos_grilla_x <", value, "numPosGrillaX");
            return this;
        }

        public Criteria andNumPosGrillaXLessThanOrEqualTo(Integer value) {
            addCriterion("num_pos_grilla_x <=", value, "numPosGrillaX");
            return this;
        }

        public Criteria andNumPosGrillaXIn(List<Integer> values) {
            addCriterion("num_pos_grilla_x in", values, "numPosGrillaX");
            return this;
        }

        public Criteria andNumPosGrillaXNotIn(List<Integer> values) {
            addCriterion("num_pos_grilla_x not in", values, "numPosGrillaX");
            return this;
        }

        public Criteria andNumPosGrillaXBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_grilla_x between", value1, value2, "numPosGrillaX");
            return this;
        }

        public Criteria andNumPosGrillaXNotBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_grilla_x not between", value1, value2, "numPosGrillaX");
            return this;
        }

        public Criteria andNumPosGrillaYIsNull() {
            addCriterion("num_pos_grilla_y is null");
            return this;
        }

        public Criteria andNumPosGrillaYIsNotNull() {
            addCriterion("num_pos_grilla_y is not null");
            return this;
        }

        public Criteria andNumPosGrillaYEqualTo(Integer value) {
            addCriterion("num_pos_grilla_y =", value, "numPosGrillaY");
            return this;
        }

        public Criteria andNumPosGrillaYNotEqualTo(Integer value) {
            addCriterion("num_pos_grilla_y <>", value, "numPosGrillaY");
            return this;
        }

        public Criteria andNumPosGrillaYGreaterThan(Integer value) {
            addCriterion("num_pos_grilla_y >", value, "numPosGrillaY");
            return this;
        }

        public Criteria andNumPosGrillaYGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_pos_grilla_y >=", value, "numPosGrillaY");
            return this;
        }

        public Criteria andNumPosGrillaYLessThan(Integer value) {
            addCriterion("num_pos_grilla_y <", value, "numPosGrillaY");
            return this;
        }

        public Criteria andNumPosGrillaYLessThanOrEqualTo(Integer value) {
            addCriterion("num_pos_grilla_y <=", value, "numPosGrillaY");
            return this;
        }

        public Criteria andNumPosGrillaYIn(List<Integer> values) {
            addCriterion("num_pos_grilla_y in", values, "numPosGrillaY");
            return this;
        }

        public Criteria andNumPosGrillaYNotIn(List<Integer> values) {
            addCriterion("num_pos_grilla_y not in", values, "numPosGrillaY");
            return this;
        }

        public Criteria andNumPosGrillaYBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_grilla_y between", value1, value2, "numPosGrillaY");
            return this;
        }

        public Criteria andNumPosGrillaYNotBetween(Integer value1, Integer value2) {
            addCriterion("num_pos_grilla_y not between", value1, value2, "numPosGrillaY");
            return this;
        }

        public Criteria andNumDimGrillaXIsNull() {
            addCriterion("num_dim_grilla_x is null");
            return this;
        }

        public Criteria andNumDimGrillaXIsNotNull() {
            addCriterion("num_dim_grilla_x is not null");
            return this;
        }

        public Criteria andNumDimGrillaXEqualTo(Integer value) {
            addCriterion("num_dim_grilla_x =", value, "numDimGrillaX");
            return this;
        }

        public Criteria andNumDimGrillaXNotEqualTo(Integer value) {
            addCriterion("num_dim_grilla_x <>", value, "numDimGrillaX");
            return this;
        }

        public Criteria andNumDimGrillaXGreaterThan(Integer value) {
            addCriterion("num_dim_grilla_x >", value, "numDimGrillaX");
            return this;
        }

        public Criteria andNumDimGrillaXGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_dim_grilla_x >=", value, "numDimGrillaX");
            return this;
        }

        public Criteria andNumDimGrillaXLessThan(Integer value) {
            addCriterion("num_dim_grilla_x <", value, "numDimGrillaX");
            return this;
        }

        public Criteria andNumDimGrillaXLessThanOrEqualTo(Integer value) {
            addCriterion("num_dim_grilla_x <=", value, "numDimGrillaX");
            return this;
        }

        public Criteria andNumDimGrillaXIn(List<Integer> values) {
            addCriterion("num_dim_grilla_x in", values, "numDimGrillaX");
            return this;
        }

        public Criteria andNumDimGrillaXNotIn(List<Integer> values) {
            addCriterion("num_dim_grilla_x not in", values, "numDimGrillaX");
            return this;
        }

        public Criteria andNumDimGrillaXBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_grilla_x between", value1, value2, "numDimGrillaX");
            return this;
        }

        public Criteria andNumDimGrillaXNotBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_grilla_x not between", value1, value2, "numDimGrillaX");
            return this;
        }

        public Criteria andNumDimGrillaYIsNull() {
            addCriterion("num_dim_grilla_y is null");
            return this;
        }

        public Criteria andNumDimGrillaYIsNotNull() {
            addCriterion("num_dim_grilla_y is not null");
            return this;
        }

        public Criteria andNumDimGrillaYEqualTo(Integer value) {
            addCriterion("num_dim_grilla_y =", value, "numDimGrillaY");
            return this;
        }

        public Criteria andNumDimGrillaYNotEqualTo(Integer value) {
            addCriterion("num_dim_grilla_y <>", value, "numDimGrillaY");
            return this;
        }

        public Criteria andNumDimGrillaYGreaterThan(Integer value) {
            addCriterion("num_dim_grilla_y >", value, "numDimGrillaY");
            return this;
        }

        public Criteria andNumDimGrillaYGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_dim_grilla_y >=", value, "numDimGrillaY");
            return this;
        }

        public Criteria andNumDimGrillaYLessThan(Integer value) {
            addCriterion("num_dim_grilla_y <", value, "numDimGrillaY");
            return this;
        }

        public Criteria andNumDimGrillaYLessThanOrEqualTo(Integer value) {
            addCriterion("num_dim_grilla_y <=", value, "numDimGrillaY");
            return this;
        }

        public Criteria andNumDimGrillaYIn(List<Integer> values) {
            addCriterion("num_dim_grilla_y in", values, "numDimGrillaY");
            return this;
        }

        public Criteria andNumDimGrillaYNotIn(List<Integer> values) {
            addCriterion("num_dim_grilla_y not in", values, "numDimGrillaY");
            return this;
        }

        public Criteria andNumDimGrillaYBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_grilla_y between", value1, value2, "numDimGrillaY");
            return this;
        }

        public Criteria andNumDimGrillaYNotBetween(Integer value1, Integer value2) {
            addCriterion("num_dim_grilla_y not between", value1, value2, "numDimGrillaY");
            return this;
        }

        public Criteria andIndMouseVisualizadoIsNull() {
            addCriterion("ind_mouse_visualizado is null");
            return this;
        }

        public Criteria andIndMouseVisualizadoIsNotNull() {
            addCriterion("ind_mouse_visualizado is not null");
            return this;
        }

        public Criteria andIndMouseVisualizadoEqualTo(String value) {
            addCriterion("ind_mouse_visualizado =", value, "indMouseVisualizado");
            return this;
        }

        public Criteria andIndMouseVisualizadoNotEqualTo(String value) {
            addCriterion("ind_mouse_visualizado <>", value, "indMouseVisualizado");
            return this;
        }

        public Criteria andIndMouseVisualizadoGreaterThan(String value) {
            addCriterion("ind_mouse_visualizado >", value, "indMouseVisualizado");
            return this;
        }

        public Criteria andIndMouseVisualizadoGreaterThanOrEqualTo(String value) {
            addCriterion("ind_mouse_visualizado >=", value, "indMouseVisualizado");
            return this;
        }

        public Criteria andIndMouseVisualizadoLessThan(String value) {
            addCriterion("ind_mouse_visualizado <", value, "indMouseVisualizado");
            return this;
        }

        public Criteria andIndMouseVisualizadoLessThanOrEqualTo(String value) {
            addCriterion("ind_mouse_visualizado <=", value, "indMouseVisualizado");
            return this;
        }

        public Criteria andIndMouseVisualizadoLike(String value) {
            addCriterion("ind_mouse_visualizado like", value, "indMouseVisualizado");
            return this;
        }

        public Criteria andIndMouseVisualizadoNotLike(String value) {
            addCriterion("ind_mouse_visualizado not like", value, "indMouseVisualizado");
            return this;
        }

        public Criteria andIndMouseVisualizadoIn(List<String> values) {
            addCriterion("ind_mouse_visualizado in", values, "indMouseVisualizado");
            return this;
        }

        public Criteria andIndMouseVisualizadoNotIn(List<String> values) {
            addCriterion("ind_mouse_visualizado not in", values, "indMouseVisualizado");
            return this;
        }

        public Criteria andIndMouseVisualizadoBetween(String value1, String value2) {
            addCriterion("ind_mouse_visualizado between", value1, value2, "indMouseVisualizado");
            return this;
        }

        public Criteria andIndMouseVisualizadoNotBetween(String value1, String value2) {
            addCriterion("ind_mouse_visualizado not between", value1, value2, "indMouseVisualizado");
            return this;
        }
    }
}