package pe.com.certicom.scolas.model.beans;

public class GrillaLlamados {

    public void setFontsSupported(String fonts){
        if(fonts!=null && fonts.trim().length()>0){
            String[] fontsArray = fonts.split(",");
            for(String font:fontsArray){
                if(font.equalsIgnoreCase(this.getDesTipoFuente())){
                    this.setFontSupported(true);
                    break;
                }
            }
        }
    }

    private boolean fontSupported = false;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.id_grilla_llamados
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer idGrillaLlamados;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_filas
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numFilas;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_columnas
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColumnas;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_fondo_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorFondoR;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_fondo_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorFondoG;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_fondo_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorFondoB;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_texto_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorTextoR;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_texto_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorTextoG;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_texto_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorTextoB;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_resaltado_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorResaltadoR;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_resaltado_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorResaltadoG;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_resaltado_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorResaltadoB;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.des_tipo_fuente
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private String desTipoFuente;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_tamanio_fuente
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numTamanioFuente;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_tiempo_blinking
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numTiempoBlinking;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.des_ruta_sonido_llamado
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private String desRutaSonidoLlamado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_codigo_impresion_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorCodigoImpresionR;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_codigo_impresion_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorCodigoImpresionG;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_codigo_impresion_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorCodigoImpresionB;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_flecha_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorFlechaR;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_flecha_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorFlechaG;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_flecha_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorFlechaB;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_ventanilla_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorVentanillaR;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_ventanilla_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorVentanillaG;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column grilla_llamados.num_color_ventanilla_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    private Integer numColorVentanillaB;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.id_grilla_llamados
     *
     * @return the value of grilla_llamados.id_grilla_llamados
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getIdGrillaLlamados() {
        return idGrillaLlamados;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.id_grilla_llamados
     *
     * @param idGrillaLlamados the value for grilla_llamados.id_grilla_llamados
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setIdGrillaLlamados(Integer idGrillaLlamados) {
        this.idGrillaLlamados = idGrillaLlamados;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_filas
     *
     * @return the value of grilla_llamados.num_filas
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumFilas() {
        return numFilas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_filas
     *
     * @param numFilas the value for grilla_llamados.num_filas
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumFilas(Integer numFilas) {
        this.numFilas = numFilas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_columnas
     *
     * @return the value of grilla_llamados.num_columnas
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColumnas() {
        return numColumnas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_columnas
     *
     * @param numColumnas the value for grilla_llamados.num_columnas
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColumnas(Integer numColumnas) {
        this.numColumnas = numColumnas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_fondo_R
     *
     * @return the value of grilla_llamados.num_color_fondo_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorFondoR() {
        return numColorFondoR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_fondo_R
     *
     * @param numColorFondoR the value for grilla_llamados.num_color_fondo_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorFondoR(Integer numColorFondoR) {
        this.numColorFondoR = numColorFondoR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_fondo_G
     *
     * @return the value of grilla_llamados.num_color_fondo_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorFondoG() {
        return numColorFondoG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_fondo_G
     *
     * @param numColorFondoG the value for grilla_llamados.num_color_fondo_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorFondoG(Integer numColorFondoG) {
        this.numColorFondoG = numColorFondoG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_fondo_B
     *
     * @return the value of grilla_llamados.num_color_fondo_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorFondoB() {
        return numColorFondoB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_fondo_B
     *
     * @param numColorFondoB the value for grilla_llamados.num_color_fondo_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorFondoB(Integer numColorFondoB) {
        this.numColorFondoB = numColorFondoB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_texto_R
     *
     * @return the value of grilla_llamados.num_color_texto_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorTextoR() {
        return numColorTextoR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_texto_R
     *
     * @param numColorTextoR the value for grilla_llamados.num_color_texto_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorTextoR(Integer numColorTextoR) {
        this.numColorTextoR = numColorTextoR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_texto_G
     *
     * @return the value of grilla_llamados.num_color_texto_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorTextoG() {
        return numColorTextoG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_texto_G
     *
     * @param numColorTextoG the value for grilla_llamados.num_color_texto_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorTextoG(Integer numColorTextoG) {
        this.numColorTextoG = numColorTextoG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_texto_B
     *
     * @return the value of grilla_llamados.num_color_texto_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorTextoB() {
        return numColorTextoB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_texto_B
     *
     * @param numColorTextoB the value for grilla_llamados.num_color_texto_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorTextoB(Integer numColorTextoB) {
        this.numColorTextoB = numColorTextoB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_resaltado_R
     *
     * @return the value of grilla_llamados.num_color_resaltado_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorResaltadoR() {
        return numColorResaltadoR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_resaltado_R
     *
     * @param numColorResaltadoR the value for grilla_llamados.num_color_resaltado_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorResaltadoR(Integer numColorResaltadoR) {
        this.numColorResaltadoR = numColorResaltadoR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_resaltado_G
     *
     * @return the value of grilla_llamados.num_color_resaltado_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorResaltadoG() {
        return numColorResaltadoG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_resaltado_G
     *
     * @param numColorResaltadoG the value for grilla_llamados.num_color_resaltado_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorResaltadoG(Integer numColorResaltadoG) {
        this.numColorResaltadoG = numColorResaltadoG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_resaltado_B
     *
     * @return the value of grilla_llamados.num_color_resaltado_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorResaltadoB() {
        return numColorResaltadoB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_resaltado_B
     *
     * @param numColorResaltadoB the value for grilla_llamados.num_color_resaltado_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorResaltadoB(Integer numColorResaltadoB) {
        this.numColorResaltadoB = numColorResaltadoB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.des_tipo_fuente
     *
     * @return the value of grilla_llamados.des_tipo_fuente
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public String getDesTipoFuente() {
        return desTipoFuente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.des_tipo_fuente
     *
     * @param desTipoFuente the value for grilla_llamados.des_tipo_fuente
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setDesTipoFuente(String desTipoFuente) {
        this.desTipoFuente = desTipoFuente == null ? null : desTipoFuente.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_tamanio_fuente
     *
     * @return the value of grilla_llamados.num_tamanio_fuente
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumTamanioFuente() {
        return numTamanioFuente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_tamanio_fuente
     *
     * @param numTamanioFuente the value for grilla_llamados.num_tamanio_fuente
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumTamanioFuente(Integer numTamanioFuente) {
        this.numTamanioFuente = numTamanioFuente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_tiempo_blinking
     *
     * @return the value of grilla_llamados.num_tiempo_blinking
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumTiempoBlinking() {
        return numTiempoBlinking;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_tiempo_blinking
     *
     * @param numTiempoBlinking the value for grilla_llamados.num_tiempo_blinking
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumTiempoBlinking(Integer numTiempoBlinking) {
        this.numTiempoBlinking = numTiempoBlinking;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.des_ruta_sonido_llamado
     *
     * @return the value of grilla_llamados.des_ruta_sonido_llamado
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public String getDesRutaSonidoLlamado() {
        return desRutaSonidoLlamado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.des_ruta_sonido_llamado
     *
     * @param desRutaSonidoLlamado the value for grilla_llamados.des_ruta_sonido_llamado
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setDesRutaSonidoLlamado(String desRutaSonidoLlamado) {
        this.desRutaSonidoLlamado = desRutaSonidoLlamado == null ? null : desRutaSonidoLlamado.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_codigo_impresion_R
     *
     * @return the value of grilla_llamados.num_color_codigo_impresion_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorCodigoImpresionR() {
        return numColorCodigoImpresionR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_codigo_impresion_R
     *
     * @param numColorCodigoImpresionR the value for grilla_llamados.num_color_codigo_impresion_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorCodigoImpresionR(Integer numColorCodigoImpresionR) {
        this.numColorCodigoImpresionR = numColorCodigoImpresionR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_codigo_impresion_G
     *
     * @return the value of grilla_llamados.num_color_codigo_impresion_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorCodigoImpresionG() {
        return numColorCodigoImpresionG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_codigo_impresion_G
     *
     * @param numColorCodigoImpresionG the value for grilla_llamados.num_color_codigo_impresion_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorCodigoImpresionG(Integer numColorCodigoImpresionG) {
        this.numColorCodigoImpresionG = numColorCodigoImpresionG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_codigo_impresion_B
     *
     * @return the value of grilla_llamados.num_color_codigo_impresion_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorCodigoImpresionB() {
        return numColorCodigoImpresionB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_codigo_impresion_B
     *
     * @param numColorCodigoImpresionB the value for grilla_llamados.num_color_codigo_impresion_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorCodigoImpresionB(Integer numColorCodigoImpresionB) {
        this.numColorCodigoImpresionB = numColorCodigoImpresionB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_flecha_R
     *
     * @return the value of grilla_llamados.num_color_flecha_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorFlechaR() {
        return numColorFlechaR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_flecha_R
     *
     * @param numColorFlechaR the value for grilla_llamados.num_color_flecha_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorFlechaR(Integer numColorFlechaR) {
        this.numColorFlechaR = numColorFlechaR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_flecha_G
     *
     * @return the value of grilla_llamados.num_color_flecha_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorFlechaG() {
        return numColorFlechaG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_flecha_G
     *
     * @param numColorFlechaG the value for grilla_llamados.num_color_flecha_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorFlechaG(Integer numColorFlechaG) {
        this.numColorFlechaG = numColorFlechaG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_flecha_B
     *
     * @return the value of grilla_llamados.num_color_flecha_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorFlechaB() {
        return numColorFlechaB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_flecha_B
     *
     * @param numColorFlechaB the value for grilla_llamados.num_color_flecha_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorFlechaB(Integer numColorFlechaB) {
        this.numColorFlechaB = numColorFlechaB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_ventanilla_R
     *
     * @return the value of grilla_llamados.num_color_ventanilla_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorVentanillaR() {
        return numColorVentanillaR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_ventanilla_R
     *
     * @param numColorVentanillaR the value for grilla_llamados.num_color_ventanilla_R
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorVentanillaR(Integer numColorVentanillaR) {
        this.numColorVentanillaR = numColorVentanillaR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_ventanilla_G
     *
     * @return the value of grilla_llamados.num_color_ventanilla_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorVentanillaG() {
        return numColorVentanillaG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_ventanilla_G
     *
     * @param numColorVentanillaG the value for grilla_llamados.num_color_ventanilla_G
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorVentanillaG(Integer numColorVentanillaG) {
        this.numColorVentanillaG = numColorVentanillaG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column grilla_llamados.num_color_ventanilla_B
     *
     * @return the value of grilla_llamados.num_color_ventanilla_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public Integer getNumColorVentanillaB() {
        return numColorVentanillaB;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column grilla_llamados.num_color_ventanilla_B
     *
     * @param numColorVentanillaB the value for grilla_llamados.num_color_ventanilla_B
     *
     * @ibatorgenerated Thu Dec 15 15:52:46 COT 2011
     */
    public void setNumColorVentanillaB(Integer numColorVentanillaB) {
        this.numColorVentanillaB = numColorVentanillaB;
    }

    /**
     * @return the fontSupported
     */
    public boolean isFontSupported() {
        return fontSupported;
    }

    /**
     * @param fontSupported the fontSupported to set
     */
    public void setFontSupported(boolean fontSupported) {
        this.fontSupported = fontSupported;
    }
}