package pe.com.certicom.scolas.model.beans;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class VideoExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public VideoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    protected VideoExample(VideoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table VIDEO
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdVideoIsNull() {
            addCriterion("id_video is null");
            return this;
        }

        public Criteria andIdVideoIsNotNull() {
            addCriterion("id_video is not null");
            return this;
        }

        public Criteria andIdVideoEqualTo(Integer value) {
            addCriterion("id_video =", value, "idVideo");
            return this;
        }

        public Criteria andIdVideoNotEqualTo(Integer value) {
            addCriterion("id_video <>", value, "idVideo");
            return this;
        }

        public Criteria andIdVideoGreaterThan(Integer value) {
            addCriterion("id_video >", value, "idVideo");
            return this;
        }

        public Criteria andIdVideoGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_video >=", value, "idVideo");
            return this;
        }

        public Criteria andIdVideoLessThan(Integer value) {
            addCriterion("id_video <", value, "idVideo");
            return this;
        }

        public Criteria andIdVideoLessThanOrEqualTo(Integer value) {
            addCriterion("id_video <=", value, "idVideo");
            return this;
        }

        public Criteria andIdVideoIn(List<Integer> values) {
            addCriterion("id_video in", values, "idVideo");
            return this;
        }

        public Criteria andIdVideoNotIn(List<Integer> values) {
            addCriterion("id_video not in", values, "idVideo");
            return this;
        }

        public Criteria andIdVideoBetween(Integer value1, Integer value2) {
            addCriterion("id_video between", value1, value2, "idVideo");
            return this;
        }

        public Criteria andIdVideoNotBetween(Integer value1, Integer value2) {
            addCriterion("id_video not between", value1, value2, "idVideo");
            return this;
        }

        public Criteria andDesVideoIsNull() {
            addCriterion("des_video is null");
            return this;
        }

        public Criteria andDesVideoIsNotNull() {
            addCriterion("des_video is not null");
            return this;
        }

        public Criteria andDesVideoEqualTo(String value) {
            addCriterion("des_video =", value, "desVideo");
            return this;
        }

        public Criteria andDesVideoNotEqualTo(String value) {
            addCriterion("des_video <>", value, "desVideo");
            return this;
        }

        public Criteria andDesVideoGreaterThan(String value) {
            addCriterion("des_video >", value, "desVideo");
            return this;
        }

        public Criteria andDesVideoGreaterThanOrEqualTo(String value) {
            addCriterion("des_video >=", value, "desVideo");
            return this;
        }

        public Criteria andDesVideoLessThan(String value) {
            addCriterion("des_video <", value, "desVideo");
            return this;
        }

        public Criteria andDesVideoLessThanOrEqualTo(String value) {
            addCriterion("des_video <=", value, "desVideo");
            return this;
        }

        public Criteria andDesVideoLike(String value) {
            addCriterion("des_video like", value, "desVideo");
            return this;
        }

        public Criteria andDesVideoNotLike(String value) {
            addCriterion("des_video not like", value, "desVideo");
            return this;
        }

        public Criteria andDesVideoIn(List<String> values) {
            addCriterion("des_video in", values, "desVideo");
            return this;
        }

        public Criteria andDesVideoNotIn(List<String> values) {
            addCriterion("des_video not in", values, "desVideo");
            return this;
        }

        public Criteria andDesVideoBetween(String value1, String value2) {
            addCriterion("des_video between", value1, value2, "desVideo");
            return this;
        }

        public Criteria andDesVideoNotBetween(String value1, String value2) {
            addCriterion("des_video not between", value1, value2, "desVideo");
            return this;
        }

        public Criteria andDesRutaVideoIsNull() {
            addCriterion("des_ruta_video is null");
            return this;
        }

        public Criteria andDesRutaVideoIsNotNull() {
            addCriterion("des_ruta_video is not null");
            return this;
        }

        public Criteria andDesRutaVideoEqualTo(String value) {
            addCriterion("des_ruta_video =", value, "desRutaVideo");
            return this;
        }

        public Criteria andDesRutaVideoNotEqualTo(String value) {
            addCriterion("des_ruta_video <>", value, "desRutaVideo");
            return this;
        }

        public Criteria andDesRutaVideoGreaterThan(String value) {
            addCriterion("des_ruta_video >", value, "desRutaVideo");
            return this;
        }

        public Criteria andDesRutaVideoGreaterThanOrEqualTo(String value) {
            addCriterion("des_ruta_video >=", value, "desRutaVideo");
            return this;
        }

        public Criteria andDesRutaVideoLessThan(String value) {
            addCriterion("des_ruta_video <", value, "desRutaVideo");
            return this;
        }

        public Criteria andDesRutaVideoLessThanOrEqualTo(String value) {
            addCriterion("des_ruta_video <=", value, "desRutaVideo");
            return this;
        }

        public Criteria andDesRutaVideoLike(String value) {
            addCriterion("des_ruta_video like", value, "desRutaVideo");
            return this;
        }

        public Criteria andDesRutaVideoNotLike(String value) {
            addCriterion("des_ruta_video not like", value, "desRutaVideo");
            return this;
        }

        public Criteria andDesRutaVideoIn(List<String> values) {
            addCriterion("des_ruta_video in", values, "desRutaVideo");
            return this;
        }

        public Criteria andDesRutaVideoNotIn(List<String> values) {
            addCriterion("des_ruta_video not in", values, "desRutaVideo");
            return this;
        }

        public Criteria andDesRutaVideoBetween(String value1, String value2) {
            addCriterion("des_ruta_video between", value1, value2, "desRutaVideo");
            return this;
        }

        public Criteria andDesRutaVideoNotBetween(String value1, String value2) {
            addCriterion("des_ruta_video not between", value1, value2, "desRutaVideo");
            return this;
        }

        public Criteria andIndActivoIsNull() {
            addCriterion("ind_activo is null");
            return this;
        }

        public Criteria andIndActivoIsNotNull() {
            addCriterion("ind_activo is not null");
            return this;
        }

        public Criteria andIndActivoEqualTo(String value) {
            addCriterion("ind_activo =", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoNotEqualTo(String value) {
            addCriterion("ind_activo <>", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoGreaterThan(String value) {
            addCriterion("ind_activo >", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoGreaterThanOrEqualTo(String value) {
            addCriterion("ind_activo >=", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoLessThan(String value) {
            addCriterion("ind_activo <", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoLessThanOrEqualTo(String value) {
            addCriterion("ind_activo <=", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoLike(String value) {
            addCriterion("ind_activo like", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoNotLike(String value) {
            addCriterion("ind_activo not like", value, "indActivo");
            return this;
        }

        public Criteria andIndActivoIn(List<String> values) {
            addCriterion("ind_activo in", values, "indActivo");
            return this;
        }

        public Criteria andIndActivoNotIn(List<String> values) {
            addCriterion("ind_activo not in", values, "indActivo");
            return this;
        }

        public Criteria andIndActivoBetween(String value1, String value2) {
            addCriterion("ind_activo between", value1, value2, "indActivo");
            return this;
        }

        public Criteria andIndActivoNotBetween(String value1, String value2) {
            addCriterion("ind_activo not between", value1, value2, "indActivo");
            return this;
        }
    }
}