package pe.com.certicom.scolas.model.beans;

public class Video {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VIDEO.id_video
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    private Integer idVideo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VIDEO.des_video
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    private String desVideo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VIDEO.des_ruta_video
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    private String desRutaVideo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column VIDEO.ind_activo
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    private String indActivo;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VIDEO.id_video
     *
     * @return the value of VIDEO.id_video
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public Integer getIdVideo() {
        return idVideo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VIDEO.id_video
     *
     * @param idVideo the value for VIDEO.id_video
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void setIdVideo(Integer idVideo) {
        this.idVideo = idVideo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VIDEO.des_video
     *
     * @return the value of VIDEO.des_video
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public String getDesVideo() {
        return desVideo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VIDEO.des_video
     *
     * @param desVideo the value for VIDEO.des_video
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void setDesVideo(String desVideo) {
        this.desVideo = desVideo == null ? null : desVideo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VIDEO.des_ruta_video
     *
     * @return the value of VIDEO.des_ruta_video
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public String getDesRutaVideo() {
        return desRutaVideo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VIDEO.des_ruta_video
     *
     * @param desRutaVideo the value for VIDEO.des_ruta_video
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void setDesRutaVideo(String desRutaVideo) {
        this.desRutaVideo = desRutaVideo == null ? null : desRutaVideo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column VIDEO.ind_activo
     *
     * @return the value of VIDEO.ind_activo
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public String getIndActivo() {
        return indActivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column VIDEO.ind_activo
     *
     * @param indActivo the value for VIDEO.ind_activo
     *
     * @ibatorgenerated Sun Dec 11 16:55:16 COT 2011
     */
    public void setIndActivo(String indActivo) {
        this.indActivo = indActivo == null ? null : indActivo.trim();
    }
}